### ISSUE TITLE
Planejamento dos desafios e linhas temáticas

### ISSUE THREAD

**Issue by Sircorujo** [LabCDBr/gestao#101]
Definição das áreas para premiação.

**Comment by wforte88** [comment]
@uira @Andreqlp conseguem dar um apoio para o @Sircorujo da definição dessas áreas temáticas?

**Comment by Andreqlp** [comment]
Pensando alto, poderia ser:
- visualização de dados
- acessibiliade
- agenda cultural
- metodologias de contagem de público
- fortalecimento da rede entre artistas e produtores
- automatização na conferência de documentação
-

**Comment by Sircorujo** [comment]
Foi escolhida a questão da acessibilidade em localidades remotas como desafio a ser trabalhado.
