### ISSUE TITLE
[Épico] Primeira Oficina de Design de Soluções Digitais

### ISSUE THREAD

**Issue by uira** [LabCDBr/gestao#104]
**Escopo**
É preciso realizar uma Oficina de Design mapearmos algum nível de detalhamento dos produtos que foram propostos no TED. Essas informações são fundamentais para subsidiar muitas das entregas previstas, além de criar um Backlog de possibilidade para implementações futuras.

- [x] #105
- [x] #106
- [x] #107
- [x] #109
- [x] #129 
- [x] #130

**Comment by RaniGub** [comment]
@wforte88 não consigo tagear essa issue como Épico.

**Comment by uira** [comment]
Com louvor! <3
