### ISSUE TITLE
Entrega/Publicação dos Resultados da 1a Oficina de Design

### ISSUE THREAD

**Issue by uira** [LabCDBr/gestao#110]
**Escopo**
É preciso fechar um produto que comunique os resultados da Oficina para as pessoas participantes.

- [ ] #129
- [ ] #130

**Comment by RaniGub** [comment]
Essa tarefa está sendo finalizado por mim e pelo @marlioesmeraldo

**Comment by diegonrojas** [comment]
A parte da tarefa que está sendo feita para a Web está aqui em versão preliminar: https://pnabsolucoes.mapas.tec.br/oficina-de-design/

**Comment by marlioesmeraldo** [comment]
PDF entregue: https://drive.google.com/file/d/1w1B9xNeH4YUlvqPC1kDBZ9UbcgD55IAw/view?usp=sharing

**Comment by RaniGub** [comment]
Olá pessoal, essa tarefa está duplicada, vou encerrar ela para que possamos seguir com os encaminhamentos na #129 e #130
