### ISSUE TITLE
Matriz de relacionamento das causas com as etapas do fluxo de fomento

### ISSUE THREAD

**Issue by wforte88** [LabCDBr/gestao#116]
**Escopo**
Para melhorar a visualização das necessidades mapeadas com as etapas do Fluxo de Fomento, será desenvolvida uma proposta de matriz de relacionamentos.

**Informações complementares**
https://www.figma.com/file/SGuBYJIS6jm5Ow7RRi1Gq1/Matriz-de-Relacionamento-com-o-Fluxo-de-Fomento?type=whiteboard&node-id=0%3A1&t=8kVpfNWOdi4NzYPB-1

**Comment by RaniGub** [comment]
Modelo de Matriz concluída. Precisamos agora relacionar cada necessidade mapeada na oficina com sua respectiva etapa no Fluxo. Vou alinhar com o @Andreqlp a explicação para ele fazer isso no assíncrono.

**Comment by Andreqlp** [comment]
@RaniGub e @wforte88 a matriz foi atualizada.
