### ISSUE TITLE
Arquitetura da Informação mínima do Mapas Culturais v7

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#117]
**Escopo**
Precisamos entender a Arquitetura de rotas mínimas para atender aos requisitos do relatório de acessibilidade.

Rotas primárias:
Home: https://mapas.tec.br/
Oportunidades: https://mapas.tec.br/oportunidades/
Agentes: https://mapas.tec.br/agentes/
Eventos: https://mapas.tec.br/eventos/
Espaços: https://mapas.tec.br/espacos/
Projetos: https://mapas.tec.br/projetos/
Cadastro: https://mapas.tec.br/autenticacao/register/
Perfil: Aguardando correção técnica para acessar

**Comment by RaniGub** [comment]
@lpirola você pode usar como referências para mapeamento das rotas a AI V1.1 do Mapa da Saúde.

https://www.figma.com/file/rMFUNO9FjkBxejQRlinCsb/AI-Mapa-da-Sa%C3%BAde---V1.1?type=whiteboard&t=x0Iu2jGxmkY3DChc-6

**Comment by RaniGub** [comment]
Adicionei como registro as rotas primárias no escopo. Precisamos ir em outros níveis para saber se há necessidade de adicionar mais rotas com base no comportamento dos elementos presentes em cada um. Aparentemente são redundantes.

**Comment by lpirola** [comment]
Eu deixei dessa forma:

1. 
2. Login
3. Visualização do perfil do usuário
4. Edição do perfil do usuário
5. Listagem de oportunidades
6. Inscrição em uma oportunidade
7. Resultados da oportunidade
8. Página Inicial
9. Visualização dos eventos
10. Edição dos eventos
11. Visualização dos espaços
12. Edição dos espaços
13. Visualização dos projetos
14. Edição dos projetos

**Comment by RaniGub** [comment]
> Eu deixei dessa forma:
> 
> 2. Login
> 3. Visualização do perfil do usuário
> 4. Edição do perfil do usuário
> 5. Listagem de oportunidades
> 6. Inscrição em uma oportunidade
> 7. Resultados da oportunidade
> 8. Página Inicial
> 9. Visualização dos eventos
> 10. Edição dos eventos
> 11. Visualização dos espaços
> 12. Edição dos espaço
> 13. Visualização dos projetos
> 14. Edição dos projetos

Oi @lpirola massa, ficou faltando você digitar o que seria o tópico 1. Fiquei na dúvida se não entraria a parte de **criação** de perfil, oportunidades, eventos e espaços.
