### ISSUE TITLE
PDF de apresentação dos resultados da Oficina de Design

### ISSUE THREAD

**Issue by diegonrojas** [LabCDBr/gestao#129]

**Comment by marlioesmeraldo** [comment]
PDF entregue: https://drive.google.com/file/d/1w1B9xNeH4YUlvqPC1kDBZ9UbcgD55IAw/view?usp=sharing

**Comment by RaniGub** [comment]
PDF entregue pelo Márlio, Juliana enviou para revisão com a Ascom.
