### ISSUE TITLE
Página Web de apresentação dos resultados da Oficina de Design

### ISSUE THREAD

**Issue by diegonrojas** [LabCDBr/gestao#130]

**Comment by RaniGub** [comment]
Página em processo de finalização
https://pnabsolucoes.mapas.tec.br/oficina-de-design/

**Comment by diegonrojas** [comment]
Novo endereço da página: https://solucoesdigitais.mapas.tec.br/oficina-de-design/

Precisa ser revista com a equipe do ponto de vista de conteúdo.

Precisa ser revisto o frontend no Mobile

**Comment by uira** [comment]
Aprovado.

## Débitos técnicos
- [ ] Mover fotos do evento e link do flickr para o final, antes do call to action da Rede Mapas.
- [ ] Retirar links de imagens (as imagens dos 7 passos estão linkadas para elas mesmas)
- [ ] No call to action das Necessidades, o link deve ser específico, direto para o quadro de necessidades dentro do Quado Figma da Oficina

**Comment by diegonrojas** [comment]
Consegui o link da seção sobre as Necessidades com a ajuda do Márlio

https://www.figma.com/file/E2A3nWY3AJ6PhSaf697645/Resultados-%7C-Oficina-de-Design-MinC-Fev%2F2024?type=whiteboard&node-id=2002-9194&t=Mrt3603tZLRFmaRp-4

Criando link curto na gralha

**Comment by diegonrojas** [comment]
Feito: https://gralha.cc/FigmaOficinaDeDesignNecessidades

**Comment by diegonrojas** [comment]
Atualizado no site o link
