### ISSUE TITLE
Elaboração de uma recomendação de estratégia de migração

### ISSUE THREAD

**Issue by wforte88** [LabCDBr/gestao#136]

**Comment by lpirola** [comment]
Ao invés de focar em uma única recomendação foi organizado no documento alguns questionamentos e etapas em formato de orientações gerais a serem utilizadas para desenhar a estratégia de migração.

**Comment by RaniGub** [comment]
> Ao invés de focar em uma única recomendação foi organizado no documento alguns questionamentos e etapas em formato de orientações gerais a serem utilizadas para desenhar a estratégia de migração.

Oi Lucas, você tem o link desse documento?

**Comment by lpirola** [comment]
https://github.com/LabCDBr/gestao/blob/main/produtos%2F2-4-PROCESSO%20DE%20ATUALIZA%C3%87%C3%83O%20DE%20VERS%C3%83O%20DO%20SOFTWARE%20MAPAS%20CULTURAIS.odt

Tá no próprio repositório
