### ISSUE TITLE
Elaboração de minuta do Plano Estratégico de Relacionamento e Governança da Rede Mapas

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#138]
### Escopo
- [x] Fechamento da minuta do Plano Estratégico: 27/03 (@marlioesmeraldo, @Narapessoa e @diegonrojas)
- [x] Revisão e validação do time de narrativas: 28/03 (@uira e @wforte88)

### Plano de Ação
27/03 10h: Reunião de fechamento da minuta do Plano Estratégico (Diego, Márlio e Nara)
28/03: Revisão e validação do time de narrativas (@uira e @wforte88)

**Comment by diegonrojas** [comment]
Estamos organizando agora tudo que foi levantado no documento neste Figma: https://www.figma.com/file/lOqZXZ9lRXoJQKEw9cSUK6/Plano-Estrat%C3%A9gico-de-Governan%C3%A7a-e-Relacionamento-com-a-Rede-Mapas?type=whiteboard&node-id=0%3A1&t=nig1j4PcAG4YGnNx-1
