### ISSUE TITLE
Levantamento de requisitos e definição de escopo

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#139]
Reuniões realizadas nos dias 19 e 20/03 entre @marlioesmeraldo, @Narapessoa e @diegonrojas para levantamento de requisitos definição de escopo.

**Comment by diegonrojas** [comment]
Levantamos todos os requisitos em um documento: https://docs.google.com/document/d/1Z_96v_UHN5dCATxGIs7N27d-2ZFlODSH_rEYvc8VOXA/edit?usp=sharing
