### ISSUE TITLE
[PROD 2.6] TR de contratação de solução digital

### ISSUE THREAD

**Issue by thaisbtoscano** [LabCDBr/gestao#14]
## Meta 2 > Produto 6
1 (um) documento contendo o modelo de Termo de Referência (TR) para Contratação de Serviço Especializado Solução Digital para Gestão do Fluxo de Fomento à Cultura, incluindo serviços de migração de dados.

### Escopo

- [x] #60
- [x] #61
- [x] #62
- [x] #63

### Critérios de aceitação
Minuta geral para validação do MinC

### Observações
A Dast tem elaborado muitos documentos para apoio a estados e municípios. Acionar eles para apoiar esse processo.

Entrega
[Doc publicado no repositório](https://github.com/LabCDBr/gestao/blob/main/produtos/2-6-TERMO%20DE%20REFER%C3%8ANCIA%20PARA%20O%20EDITAL%20DE%20CHAMAMENTO%20P%C3%9ABLICO%20N%C2%BA%20XXX_2024.odt)

**Comment by doutorsocrates90** [comment]
Produto finalizado e entregue:
https://github.com/LabCDBr/gestao/blob/main/produtos/M2%20P6%20-%20TR%20Contrata%C3%A7%C3%A3o%20Servi%C3%A7o%20Especializado%20Solu%C3%A7%C3%B5es%20Digitais.pdf
