### ISSUE TITLE
Identificação dos Gaps da V7 do Mapas em relação ao Fluxo de Fomento

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#142]
**Escopo**
Precisamos entender onde a V7 do Mapas não atende ao Fluxo de Fomento da Lei Aldir Blanc.
Essa deve ser realizada antes da #115 

**Atualização de escopo**
Os Gaps serão prioritariamente identificados com base nas indicações do MinC. As priorizações do que é essencialmente necessário foram dadas pela Sofia.

**Informações adicionais**
https://www.figma.com/file/181VOj4DVixEuGyKjfQeXT/Oficina-de-Design-Mapas---Fevereiro%2F2024?type=whiteboard&node-id=493-5344&t=5gKfnQM9pBZIHfyv-4

**Comment by RaniGub** [comment]
Preciso alinhar com o André.

**Comment by wforte88** [comment]
@lpirola e @Andreqlp aqui precisamos do apoio de vocês para identificar o que o Mapa não atende por completo no fluxo detalhado de fomento. Peço que vocês [acessem o Figma](https://www.figma.com/file/181VOj4DVixEuGyKjfQeXT/Oficina-de-Design-Mapas---Fevereiro%2F2024?type=whiteboard&node-id=493-5344&t=5gKfnQM9pBZIHfyv-4) e coloquem o sticker indicado na legenda em cada etapa que o sistema não atende completamente.

**Comment by Andreqlp** [comment]
@wforte88 fiz meus apontamentos no figma, fico no aguardo dos demais apontamentos para marcarmos uma conversa de alinhamento.

**Comment by RaniGub** [comment]
Segundo o André, o Mapas atende da Publicação do Edital (Oportunidade) à Publicação do Resultado Final da inscrição no Edital. Ele já foi fazendo alguns apontamentos de fragilidades que podem ser consideradas na melhoria da experiência. Essas marcações serão adicionadas na Matriz de Relacionamentos após alinhamento com demais pessoas.

**Comment by wforte88** [comment]
Relação inicial de pendência para atendimento ao fluxo froam registradas [neste quadro no Figma](https://www.figma.com/file/181VOj4DVixEuGyKjfQeXT/Oficina-de-Design-Mapas---Fevereiro%2F2024?type=whiteboard&node-id=493-5344&t=5gKfnQM9pBZIHfyv-4).

Mapeamento dessas informações será realizado na #151

**Comment by RaniGub** [comment]
@uira @lpirola vamos dá uma olhada nas colocações do André.

**Comment by RaniGub** [comment]
A issue foi reaberta para análise adicional.

**Comment by RaniGub** [comment]
@wforte88 entendo que essa tarefa sofreu alteração de escopo e agora ela será atendida com o movimento que estamos fazendo de priorização com o MinC. Então o presente Épico pode ser fechado com esse entendimento. Será atendido no Épico #466

**Comment by RaniGub** [comment]
A tarefa será fechada. Essa visualização está sendo possível com o preenchimento do Framework de fluxos de jornadas.
