### ISSUE TITLE
Organização de ambientes online para consulta do Roadmap

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#148]
**Escopo**
Precisamos ter um norte do encadeamento de tarefas necessárias para mapeamento de jornadas, desenho de experiência, prototipação de telas, implementação e testes de usabilidade no projeto. Essa atividade dá subsídios iniciais para o Produto 2.3.

**Informações complementares**
https://www.figma.com/file/4J3YoNRyskxStp8UeqNKew/Untitled?type=whiteboard&node-id=1%3A2&t=m0ZN9gkcryQhtNCk-1

**Comment by RaniGub** [comment]
RoadMap finalizado, tarefa movida para validação do @lpirola e @wforte88

**Comment by wforte88** [comment]
> RoadMap finalizado, tarefa movida para validação do [@lpirola](https://github.com/lpirola) e [@wforte88](https://github.com/wforte88)

@RaniGub o link está privado, não consegui visualizar.

**Comment by RaniGub** [comment]
> > RoadMap finalizado, tarefa movida para validação do [@lpirola](https://github.com/lpirola) e [@wforte88](https://github.com/wforte88)
> 
> [@RaniGub](https://github.com/RaniGub) o link está privado, não consegui visualizar.

Oi @wforte88 deu certo o convite para administrador do ambiente que lhe enviei hoje? Acabei de mandar também o convite para edição da board.
