### ISSUE TITLE
Mapeamento de Jornada | Gestora cultural

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#154]
**Escopo**
Precisamos compreender a jornada da Gestora Cultural, pessoa que disponibiliza a oportunidade de fomento.
- [x] Entrevista com Vinicius
- [x] Sistematização de informações
- [x] Adaptação de framework
- [x] Validação do fluxo pela Juliana Almeida
- [x] Ajustes na jornada com base nos comentários da Juliana
- [ ] Validação Final (Wash, Uirá, Rani)

**Informações complementares**
Pessoa de referência: Vinícus - Secult/CE

**Comment by RaniGub** [comment]
Convite feito ao Vinicius, aguardando agenda.

**Comment by RaniGub** [comment]
Agenda marcada com Vinicius para dia 16, de 10h às 12h.

**Comment by drabelodesign** [comment]
Desenvolvendo documento de Roteiro de Pesquisa para mapeamento da jornada.

**Comment by RaniGub** [comment]
Entrevista realizada com o Vinicius em 16/04.

**Comment by drabelodesign** [comment]
Desenhando o fluxo da jornada do Gestor Cultural.

**Comment by RaniGub** [comment]
Olá @drabelodesign você pode mover esse Figma para o nosso ambiente? Pode colocar na pasta Informações base. É interessante indicarmos, na jornada mapeada, a qual etapa do Fluxo de Fomento ela faz parte, para deixarmos essa relação sempre apresentada. Imagino que uma nova raia já resolva isso.

Fluxo: 1. Planejamento; 2. Processamento do chamamento público; 3. Celebração; 4. Execução / Monitoramento; 5. Prestação de Informações; e, 6. Avaliação / Comunicação de Resultados.

Você pode fazer o mesmo processo para a #155

**Comment by drabelodesign** [comment]
> Olá [@drabelodesign](https://github.com/drabelodesign) você pode mover esse Figma para o nosso ambiente? Pode colocar na pasta Informações base. É interessante indicarmos, na jornada mapeada, a qual etapa do Fluxo de Fomento ela faz parte, para deixarmos essa relação sempre apresentada. Imagino que uma nova raia já resolva isso.
> 
> Fluxo: 1. Planejamento; 2. Processamento do chamamento público; 3. Celebração; 4. Execução / Monitoramento; 5. Prestação de Informações; e, 6. Avaliação / Comunicação de Resultados.
> 
> Você pode fazer o mesmo processo para a [#155](https://github.com/LabCDBr/gestao/issues/155)

**Comment by drabelodesign** [comment]
Feito @RaniGub 
Movido para a pasta 'Informações Base'
Vou ajustar os nomes das fases conforme sugerido.

**Comment by RaniGub** [comment]
Tarefa reaberta. @drabelodesign está realizando adequações propostas pela @juscoton

**Comment by drabelodesign** [comment]
Desenho da jornada finalizado:
https://www.figma.com/file/d4Lfl4BcgzqK7VexRVtLvT/Jornadas-dos-Usu%C3%A1rios?type=design&node-id=41%3A2478&mode=design&t=77vbwlHs93dr4D6I-1

**Comment by RaniGub** [comment]
Bom dia @Jualmeida1212, você pode validar a Jornada da Gestora Cultural? Neste mesmo Figma, do lado esquerdo, temos a jornada do Agente Cultural, Avaliadora e Público que também foram finalizadas, você pode deixar seus comentário lá e sinalizar pra gente. Ainda temos a #373 que faremos atualização futura do modelo relacionando com o Fluxo de Fomento. Obrigado.

Print do Figma com as páginas
![Image](https://github.com/LabCDBr/gestao/assets/79097920/da3f9f72-bb35-4119-af05-27f624bac6e8)

**Comment by drabelodesign** [comment]
Ajustes realizados na Jornada do Gestor com base nos comentários da Juliana Almeida.

**Comment by RaniGub** [comment]
Tarefa finalizada.
