### ISSUE TITLE
Mapeamento de Jornada | Agente cultural

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#155]
**Escopo**
Precisamos compreender a jornada do Agente Cultural, pessoa proponente.
- [x] Entrevista com André
- [x] Sistematização de informações
- [x] Adaptação do framework
- [ ] Validação Final (Wash, Uirá, Rani e Ju)

**Informações complementares**
Pessoa de referência: André - Secult/CE

Mapeamento da jornada finalizado:
https://www.figma.com/file/d4Lfl4BcgzqK7VexRVtLvT/Jornadas-dos-Usu%C3%A1rios?type=design&node-id=0%3A1&mode=design&t=24QaCZ7RyAI8EIXF-1

**Comment by RaniGub** [comment]
Convite feito ao @Andreqlp, aguardando agenda.

**Comment by drabelodesign** [comment]
Desenvolvendo documento de Roteiro de Pesquisa para mapeamento da jornada.

**Comment by RaniGub** [comment]
Entrevista realizada com André em 15/04/2024.

**Comment by drabelodesign** [comment]
Desenhando o fluxo do agente cultural e organizando o documento da jornada em fases em conjunto com a @juscoton 

https://www.figma.com/file/22Vp8T2JQ3tWOYTZEZeBrY/Jornada-Andr%C3%A9-Secult%2FCE?type=whiteboard&node-id=0-1&t=DKV2xjjYL0mzXmkE-0

**Comment by RaniGub** [comment]
Tarefa revisada. @wforte88 vc acha que é importante mais alguma pessoa olhar para fecharmos a tarefa? Lembrando que veremos mais oportunidades quando forem cruzadas as necessidades e insights de funcionalidades futuras. Vamos criar uma tarefa pra isso.

**Comment by wforte88** [comment]
> Tarefa revisada. @wforte88 vc acha que é importante mais alguma pessoa olhar para fecharmos a tarefa? Lembrando que veremos mais oportunidades quando forem cruzadas as necessidades e insights de funcionalidades futuras. Vamos criar uma tarefa pra isso.

@RaniGub acho válido passar por validação final do MinC.

**Comment by RaniGub** [comment]
Bom dia @Jualmeida1212, você pode validar a Jornada do Agente Cultural? Obrigado.

**Comment by juscoton** [comment]
Jornada já foi validada por @Jualmeida1212 e já realizei as alterações sugeridas.

**Comment by RaniGub** [comment]
Necessário uma adaptação com base nas informações da Juliana/MinC. Issue será reaberta temporariamente.

**Comment by juscoton** [comment]
Adaptação finalizada, aguardando última checagem da @Jualmeida1212 para finalizar.

**Comment by RaniGub** [comment]
Ju, já fez a validação do Agente Cultural. Vamos marcar um imersivo para as jornadas @uira e @wforte88

**Comment by RaniGub** [comment]
Tarefa finalizada.
