### ISSUE TITLE
Mapeamento de Jornada | Público

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#158]
**Escopo**
Precisamos compreender a jornada do Público, pessoa que quer saber a agenda cultura do seu estado/município.
- [x] Realizar entrevista
- [ ] Sistematização de informações
- [ ] Desenho da Jornada

**Informações complementares**
Pessoa de referência: Uirá

**Comment by RaniGub** [comment]
Novo agendamento. 24/04, 9h30 às 10h. Convite enviado.

**Comment by drabelodesign** [comment]
Roteiro de pesquisa finalizado:
https://www.notion.so/Roteiro-de-Pesquisa-para-Mapeamento-da-Jornada-do-P-blico-Uir-Por-2a8d4516d1054118ae8e311962765c60?pvs=4

**Comment by drabelodesign** [comment]
Entrevista realizada.
Iniciando o processo de sistematização das informações.

**Comment by RaniGub** [comment]
Tarefa duplicada, acompanhar pela #252
