### ISSUE TITLE
[Épico] Identificação de melhorias de interface | Primeiro mapeamento

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#161]
**Escopo**
Faremos uma avaliação de interface/experiência identificando fragilidades e oportunidades de melhorias que exijam baixo esforço de implementação e possibilitem que as funcionalidades mínimas sejam executadas na visualização desktop e mobile.

Obs.: Outras melhorias serão visualizadas no mapeamento de jornadas e testes de usabilidade em nosso ambiente de homologação. No primeiro momento faremos isso no Mapa do Espírito Santo ou Pará. Logo após, em nosso ambiente de homologação.

Funcionalidade gerais:
- [x] #184
- [x] #185
- [x] #186
- [x] #187
- [x] #306
- [x] #307
- [x] #308
- [x] #309

**Comment by lpirola** [comment]
@RaniGub se quiser acessar: https://mapas.tec.br/

O usuário e senha: Admin@Local -> mapas123

Está com problema para criar oportunidade mas vai estar mais livre para criar testes de outras entidades.

**Comment by RaniGub** [comment]
> @RaniGub se quiser acessar: https://mapas.tec.br/
> 
> O usuário e senha: Admin@Local -> mapas123
> 
> Está com problema para criar oportunidade mas vai estar mais livre para criar testes de outras entidades.

Massa, pois vou fazer por ele mesmo, se até eu chegar nas oportunidades ela ainda estiver com problema, faço no do ES.

**Comment by RaniGub** [comment]
Essa atividade foi repriorizada.

**Comment by RaniGub** [comment]
A issue #306 a #309 não foi vinculada a este épico (tracked by), mas faz parte dele.

**Comment by RaniGub** [comment]
Primeira Épico da rodada de identificação de melhorias finalizado.
