### ISSUE TITLE
Manual de Identidade Visual da Rede Mapas

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#163]
Desenvolver o Manual de marca e Identidade Visual da Rede Mapas / Mapas

**Comment by Narapessoa** [comment]
Ações do mês de abril e, respectivos, responsáveis: 

1. Documentar histórico da Rede Mapas, considerando políticas públicas, legislação cultural e contexto atual - Márlio
2. Sistematizar e documentar arquitetura do ecossistema Mapas, da Rede Mapas e dos Sistemas de Mapeamento do MinC e dos Estados e do Projeto - Diego
3. Conceituar e definir identidade do Mapas e do ecossistema de Soluções Digitais para Mapeamento e Gestão Cultural (Produto / Rede Mapas / Projeto) - Marlio
4. Identificar e registrar os papéis das pessoas e entidades que compõem o ecossistema - Nara
5. Mapear Agentes da Comunidade, Lideranças, Instalações ativas do Mapas , Empresas e instituições desenvolvedoras/implementadoras de Mapas, Grupos de Discussão, Demandas /  projetos, Documentação - Nara
6.Definir Identidade Visual da Rede Mapas de forma colaborativa - Diego
7.Definir e (re)ativar canais de comunicação da Rede Mapas - Márlio
8. Definir ações táticas e parcerias para qualificar a presença da Rede Mapas na Internet - Diego

**Comment by diegonrojas** [comment]
TEste de criação de linhas de tarefas

- primeiras coisas
- segunda coisa
- terceira coisa

**Comment by marlioesmeraldo** [comment]
Detalhamento de maio será realizado na última semana de abril para priorizar as sprints atuais.

**Comment by diegonrojas** [comment]
Devido a semana com reunião com a Comunidade e com a CryptoRave no final de semana, alteramos a prioridade desse detalhamento e ele foi deslocado para ser finalizado na Sprint 5

**Comment by diegonrojas** [comment]
Previsão de entrega do detalhamento ficar para 14/05

**Comment by marlioesmeraldo** [comment]
Reunião realizada e feito alinhamento para design de documento pela @hihiumy com apoio do @diegonrojas e redação de apresentação pela @MayalaFernandes com apoio do @marlioesmeraldo .

**Comment by diegonrojas** [comment]
Feito o primeiro esforço para a entrega do guideline, foi enviado no drive o arquivo editável 

Segue a primeira versão:

[((RedeMapas))manual-id-visual-v01.pdf](https://github.com/LabCDBr/gestao/files/15488757/RedeMapas.manual-id-visual-v01.pdf)

**Comment by Narapessoa** [comment]
@marlioesmeraldo @uira @hihiumy @MayalaFernandes 

Segue link da pasta com o manual de identidade visual da Rede Mapas, que está em desenvolvimento.

(https://drive.google.com/drive/folders/1QcohaSbk-hAGKqGNohns8tti1r8LM0T4?usp=sharing)

**Comment by Narapessoa** [comment]
@marlioesmeraldo e @MayalaFernandes, por gentileza, incluir texto sobre o conceito e visão geral no manual de identidade. 

@hihiumy está complementando o manual iniciado pelo @diegonrojas

**Comment by marlioesmeraldo** [comment]
Reunião realizada e dadas orientações com referências de identidade / conceito e alinhamento realizado com @hihiumy e @MayalaFernandes na presença de @Narapessoa para encaminhamento com @diegonrojas .

**Comment by marlioesmeraldo** [comment]
@hihiumy está desenvolvendo a primeira versão do Manual de Identidade Visual no Figma:
https://www.figma.com/design/MVMEXQBK9jQiCKpm8kgK8K/Rede-Mapas?node-id=30-2&t=O72DnI95s792eAem-1

**Comment by marlioesmeraldo** [comment]
Algumas informações sobre a logo da Rede Mapas que podem constar na defesa da marca:

- A logo da Rede Mapas foi inspirada na logo do MapSys, software livre que inspirou o Mapas.
- A logo do MapSys foi criada por Uirá Porã, usando o software livre InkScape
- A logo da Rede Mapas foi criada por Valessio Brito, também usando software livre.
- Mais informações no histórico: https://docs.google.com/document/d/10d2gbj5s3mgkrSUVi-zMjSzL0--gbPMrQpXMDsXjkQ0/edit?tab=t.0#heading=h.ghsab2gbkyis

IMAGENS:

https://www.flickr.com/photos/uira/251897895/in/photolist-oabGg-o1REC-o1REz-o1REy-og3ta-2iXYth1-7h52Zj-7h17Dc-7h58FC-7h557d-7h57mE-nZQB3-nZQB2-mPUMU-mPUMS-mPUMQ-bqYRyn-mPUMP-mPUMR-niju1G-7jNfix-EFhzw-EFhzA-EFhAd-2gkY3CN-EFhA9-EFhzu-f3LwGS

https://www.flickr.com/photos/uira/250754895/in/photolist-oabGg-o1REC-o1REz-o1REy-og3ta-2iXYth1-7h52Zj-7h17Dc-7h58FC-7h557d-7h57mE-nZQB3-nZQB2-mPUMU-mPUMS-mPUMQ-bqYRyn-mPUMP-mPUMR-niju1G-7jNfix-EFhzw-EFhzA-EFhAd-2gkY3CN-EFhA9-EFhzu-f3LwGS

https://www.flickr.com/photos/uira/248931303/in/photolist-oabGg-o1REC-o1REz-o1REy-og3ta-2iXYth1-7h52Zj-7h17Dc-7h58FC-7h557d-7h57mE-nZQB3-nZQB2-mPUMU-mPUMS-mPUMQ-bqYRyn-mPUMP-mPUMR-niju1G-7jNfix-EFhzw-EFhzA-EFhAd-2gkY3CN-EFhA9-EFhzu-f3LwGS

**Comment by hihiumy** [comment]
Templates para posts quadrados (instagram e outros), stories (1080x1920), fundos de tela (bg para calls), capa de facebook e ícones foram adicionados ao arquivo com a identidade visual: https://www.figma.com/design/MVMEXQBK9jQiCKpm8kgK8K/Rede-Mapas?node-id=71-2&t=tn4mjADCXYBjXKbA-1

- Não consegui encontrar um arquivo onde explique a origem da logo para poder detalhar ela melhor na guideline

**Comment by marlioesmeraldo** [comment]
Áudio do Valessio Brito foi repassado para @hihiumy finalizar a proposta inicial de manual de identidade visual.

**Comment by marlioesmeraldo** [comment]
Solicitados ajustes finais para @hihiumy finalizar a proposta.

**Comment by marlioesmeraldo** [comment]
Proposta de manual finalizado e enviado para revisão pareada:
https://www.figma.com/design/AulvJsGBU0FQkDGZGgavby/Manual-de-Identidade-Visual-do-Mapas?node-id=30-2&t=L7uZhQNVwHUIlLfj-1

[Manual de Identidade Visual do Mapas.pdf](https://github.com/user-attachments/files/16114094/Manual.de.Identidade.Visual.do.Mapas.pdf)

**Comment by marlioesmeraldo** [comment]
Manual revisado pelo @uira  e finalizado.

### EVIDÊNCIA:



[Manual de Identidade Visual do Mapas.pdf](https://github.com/user-attachments/files/16318310/Manual.de.Identidade.Visual.do.Mapas.pdf)
