### ISSUE TITLE
Revisão e encaminhamento da devolutiva do MinC no Plano Estratégico

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#164]

**Comment by marlioesmeraldo** [comment]
@Narapessoa irá consultar se o MinC finalizou a revisão.

@marlioesmeraldo e @Narapessoa agendaram reunião para 05/04 para validar a revisão.

**Comment by marlioesmeraldo** [comment]
@Narapessoa vai avaliar e encaminhar cada comentário da devolutiva do Minc.

**Comment by diegonrojas** [comment]
Registrando aqui o documento que foi preparado pelas narrativas para organizar a devolução da revisão do MInC do Plano Estratégico: https://docs.google.com/document/d/1WYSeI2fsIMR8LtvZJVs8v3tC6wZMSjHItiGwO8DkhxY/edit?usp=sharing

**Comment by uira** [comment]
@diegonrojas Geeente... não entendi esse documento, era pra essas interações acontecerem lá nos comentários do figma... 

se era pra alinhar entre vcs posicionamento, ok, beleza. Mas agora precisa responder com a visão comum de vcs lá no figma, inclusive já implementando/incorporando as mudanças que fizerem sentido

**Comment by Narapessoa** [comment]
@marlioesmeraldo @marlioesmeraldo @uira Após alinhamento entre a equipe de narrativas, respondi a todas as dúvidas, questionamento e sugestões do Minc tanto no Figma, quanto no documento do plano de governança.

**Comment by Narapessoa** [comment]
Em reunião com Sofia e Juliana, no dia 13/05,  foi solicitado a priorização do eixo Tomada de decisão do plano de governança, modelo de sustentabilidade do ecossistema.

**Comment by marlioesmeraldo** [comment]
Atualização do Figma em curso incluindo apontamentos da @sofiamettenheim e @Jualmeida1212 . Pendente alinhamento com @uira e @wforte88 .
