### ISSUE TITLE
[PROD 3.2] 1 (um) Documento publicado no repositório do projeto contendo o mapa de oportunidades de integração de soluções digitais existentes na indústria cultural brasileira

### ISSUE THREAD

**Issue by thaisbtoscano** [LabCDBr/gestao#17]
### Objetivo
Identificar nível de integrabilidade entre dados ou funcionalidades principais das soluções mapeadas.

### Escopo
Conceber um conjunto de critérios de integrabilidade e aplicá-los nas soluções mapeadas para visualizar em um mapa o que cada uma atende e em quais camadas poderiam se integrar.

### Não escopo
Não é um mapeamento de especificação de código, interfaces ou guia de integração.

- [x] #57
- [x] #58
- [ ] #59

**Comment by Sircorujo** [comment]
Teste

- [ ] Teste
- [ ] dssaa

**Comment by Sircorujo** [comment]
https://docs.google.com/spreadsheets/d/1tbBmfDJl4B_nnwWH2GsdBOg0S9wCMwc8WNyD_nkjme8/edit#gid=2101486824

**Comment by uira** [comment]
@diegonrojas começou a trabalhar numa visualização infográfica interativa nesse link:

https://www.figma.com/file/TESlYOq54Bz5tyA4ZeavjL/Maposfera---Mapas-Culturais-v5-e-v7?type=whiteboard&node-id=2856-3924&t=XagDDhRQsFogx0OU-4

**Comment by diegonrojas** [comment]
Especificamente no quadro "Ecossistema de soluções" desse Figma ai

**Comment by doutorsocrates90** [comment]
Produto finalizado e entregue:
https://github.com/LabCDBr/gestao/blob/main/produtos/M3%20P2%20-%20Mapa%20de%20oportunidades%20de%20integra%C3%A7%C3%A3o.pdf
