### ISSUE TITLE
Conceituar e definir identidade do Mapas e do ecossistema

### ISSUE THREAD

**Issue by diegonrojas** [LabCDBr/gestao#170]
Documentar conceituação e identidade do Mapas e do ecossistema de Soluções Digitais para Mapeamento e Gestão Cultural (Produto / Rede Mapas / Projeto) incorporando contribuições de todos os entes da comunidade para encaminhar para publicação nos canais de comunicação da Rede Mapas.

### Checklist

- [x] #359
- [x] #357
- [x] #353
- [x] #358
- [x] #354
- [x] #459

**Comment by marlioesmeraldo** [comment]
Documento de texto em desenvolvimento:
https://docs.google.com/document/d/11wXhbqGllFmdHMXxy-2ZCgdN3VROg3F27FOzwu4ZEHc/edit?usp=sharing

**Comment by marlioesmeraldo** [comment]
Conceitos definidos no documentos mencionado.
