### ISSUE TITLE
Adaptar cards de vagas - Editais 15 e 17

### ISSUE THREAD

**Issue by wforte88** [LabCDBr/gestao#178]
### Escopo
- Atualizar os cards que já foram criados para as vagas com a nova data limite para inscrições: **10/04/2024**;
- Inserir frase ressaltando a necessidade de envio da documentação completa para garantir a inscrição.

- [ ] Três opções de texto para divulgação (apenas texto)
- [ ] CARD 1 - Edital 15/2024 - UX Designer Pleno
- [ ] CARD 2 - Edital 17/2024 - Cientista de Dados

**Comment by diegonrojas** [comment]
![Image](https://github.com/LabCDBr/gestao/assets/154905066/568f28e9-2d19-4948-a677-e70344452a66)
![Image](https://github.com/LabCDBr/gestao/assets/154905066/5aa4e0cc-91dd-43c0-bf84-913a140bb139)

**Comment by diegonrojas** [comment]
EVIDÊNCIA DA MSG DE TEXTO:

✅ Se você é um Cientista de Dados talentoso em busca de um projeto desafiador e gratificante, temos uma oportunidade para você.  

✅ A Fundação da Universidade Federal do Paraná (Funpar) está selecionando profissionais para atuar no Projeto de extensão "Qualificação de Soluções Digitais para Mapeamento e Gestão Cultural". 

📍Detalhes do Projeto: 
📅 Duração: 5 meses 
💰 Remuneração Bruta: R$10.000
 🌍 Trabalho Remoto com Possibilidades de Viagens (previamente agendadas).

Inscrições até 10/04/24

✅Clique no link  abaixo, acesse o edital e aproveite a oportunidade de contribuir para o avanço da gestão cultural e expandir seus horizontes profissionais. Junte-se a nós!

https://www.funpar.ufpr.br/app/editais-usuarios.php
