### ISSUE TITLE
[CARD] Edital extensão LAB

### ISSUE THREAD

**Issue by wforte88** [LabCDBr/gestao#181]
Card para divulgação em redes sociais (1080x1080)

### Informações

Edital de seleção de alunos para projeto de extensão

Laboratório de Cultura Digital

Bolsas de extensão para pessoas graduandas, mestrandas e doutorandas

Inscrições até 15 de abril.

https://forms.gle/gMBiQoMteJL9WMfS9 [Reduzir link]

[Assinatura institucional: LAB, UFPR / Proec, MinC]

**Comment by diegonrojas** [comment]
Feito o link reduzido para humanos: https://gralha.cc/EditalBolsistasLAB

**Comment by diegonrojas** [comment]
Nova versão com novo link

![cards-bolsistas-edital-01-v2](https://github.com/LabCDBr/gestao/assets/154905066/6e8def37-e7fc-4697-8e6e-e179eb6087fd)

**Comment by wforte88** [comment]
Leiaute aprovado. Fazer variação com tarja "Últimos dias".

**Comment by diegonrojas** [comment]
Começando agora a fechar essa variação.

**Comment by diegonrojas** [comment]
Card para aprovação

![Image](https://github.com/LabCDBr/gestao/assets/154905066/9b1c74a6-30f6-4539-aef4-4ba115ca56cd)

**Comment by diegonrojas** [comment]
QR-Code foi incorporado


![Image](https://github.com/LabCDBr/gestao/assets/154905066/695aa7b8-cf21-4816-badc-ad4bae42c173)

**Comment by diegonrojas** [comment]
Preferi por fazer mais uma versão

![Image](https://github.com/LabCDBr/gestao/assets/154905066/3f90bf24-3d27-46c1-99c7-d3a272cdb6eb)

**Comment by wforte88** [comment]
Leiaute aprovado, podes fechar a tarefa.

**Comment by diegonrojas** [comment]
amem gzuz
