### ISSUE TITLE
Identificação de melhorias | Perfil

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#184]
**Contexto**
Precisamos identificar melhorias de rápida implementação para possibilitar que as funcionalidades mínimas do Mapas tenham uma experiência minimamente eficiente.

**Escopo das atividades**
**Login/Cadastro**

**Nível de criticidade: alto**
- [ ] #188
Nosso ambiente de homologação não permite que sigamos com o Login após fazer o cadastro, o que impede que façamos o mapeamento adequado sem depender de instâncias como as do Pará ou Espírito Santo. Outro risco é que alguma atualização nessas outras instalações podem ter acontecido e o esforço para compreender quais foram não é adequado.

- [ ] #189
Não é possível recuperar a senha, o sistema não retorna uma ação após clique no botão. Outro ponto importante é que estamos usando a senha de Admin, o que nos dá uma visão de Administrador e enviesa o processo de mapeamento com a visão de usuário comum.

- [ ] #289
**Contexto:** Acesso ao login é via CTA “Entrar” posicionado na parte superior direita do menu. Aqui há falha  grave de acessibilidade, pois para quem não tem cadastro ainda o atalho pode passar despercebido.  
**Ocorrência:** web e mobile
**Recomendação:** Recomenda-se a utilização de dois CTAs: um para Login e um para Cadastro . Bem como alterar a nomenclatura de “Entrar” para “Acessar conta” para ficar mais acessível.  

- [ ] #290
**Contexto:** Botões “entrar” e “Criar conta” com larguras diferentes.  
**Ocorrência:** web e mobile
**Recomendação:** Padronizar todos os botões. 
 
- [ ] #291
**Contexto:** Os textos “Criar uma conta” e “Siga os passos para criar o seu cadastro no Mapa da Cultura Brasileira.” e o breadcrumb estão desalinhados. 
**Ocorrência:** web e mobile
**Recomendação:** necessário refazer o UI visando melhor organização das informações.

- [ ] #292
**Contexto:** No campo de digitar senha, não há a opção de visualizar a senha digitada, podendo ser um obstáculo para usuários com menor maturidade digital. 
**Ocorrência:** web e mobile
**Recomendação:** inserir ícone de olho no campo, com a opção de ocultar/visualizar a senha.

- [ ] #293
**Contexto:** Na segunda tela do cadastro, há o texto: “Falta pouco para finalizar o seu cadastro! Dê um nome e faça uma breve descrição do seu Agente”. Orientação deveria trazer mais clareza, podendo levar o abandono do fluxo por quem não se considera um “agente”. 
**Ocorrência:** web e mobile
**Recomendação:** rever writing e adicionar a opção de preencher esse campo depois.

- [ ] #294
**Contexto:** Campo esqueci minha senha: é informado via texto, não passando a impressão de ser clicável.  
**Ocorrência:** web e mobile
**Recomendação:** sugere-se a utilização de hiperlink, com texto em bold e sublinhado, também reposicionar abaixo dos botões. 

**Nível de criticidade: médio**
- [ ] #288
[PERFIL] Redesign da tela
**Contexto:** Qualidades e especificações do perfil podem ser melhor apresentadas
**Ocorrência:** web e mobile
**Recomendação:** Recomenda-se o redesign da tela, para melhorar a arquitetura de informação e deixá-la mais atrativa. Entender se é possível/viável refazê-la. Sugere-se a adaptação para um formato similar ao de rede social.

- [ ] #295
**Contexto:** Ao clicar em login o usuário é redirecionado para nova página, onde há estrutura de login muito extensa, ficando “esticada” na tela. O redirecionamento carrega o site e aumenta a carga cognitiva do usuário.
**Ocorrência:** web
**Recomendação:** criar nova estrutura de modal para login e para cadastro, que abre sobre a página inicial sem distorcer na tela e sem redirecionar o usuário para nova página.

- [ ] #296
**Contexto:** texto “Entre na sua conta do Mapas Culturais Base Project” não deixa claro do que Base Project se trata.
**Ocorrência:** web e mobile
**Recomendação:** Necessário rever texto e adicionar informações para trazer mais clareza.

- [ ] #297
**Contexto:** Legendas dos campos de preenchimento estão confusas, com fontes muito grande e com espaçamento distante dos campos para preencher.
**Ocorrência:** web 
**Recomendação:** rever UI e writing

- [ ] #298
**Contexto:** Disclaimer “as senhas não conferem” e “sua senha deve conter um caractere especial” aparecem na parte superior da tela e em vermelho.
**Ocorrência:** web e mobile
**Recomendação:** disclaimers aparecerem na parte central da tela e refazer UI, alterando para uma melhor estrutura em branco, com ícones de alerta e apenas o texto em vermelho.

- [ ] #299
**Contexto:** Caso o usuário não preencha vários requisitos de senha, aparece um disclaimer para cada requisito.
**Ocorrência:** web e mobile
**Recomendação:** mostrar apenas um disclaimer com os requisitos em tópicos.

** Nível de criticidade: baixo**
- [ ] #300
**Contexto:** No Cadastro o campo e-mail, ao digitar o e-mail a inicial fica com a letra maiúscula. 
**Ocorrência:** web
**Recomendação:** não automatizar a inicial maiúscula no campo e-mail.

- [ ] #301
**Contexto:** Cadastro: no campo CPF o campo “Por que pedimos este dado?” fere diretrizes de acessibilidade. 
**Ocorrência:** web e mobile
**Recomendação:** colocá-lo em cor diferente e retirar contorno.

- [ ] #302
**Contexto:** Força da senha:  Texto posicionado abaixo do campo de confirmar, recomenda-se reposicionar após o primeiro campo de preenchimento da senha.  Ao ir cumprindo as exigências de senha, a barrinha vai ficando roxa (web) ou azul (mobile). Cor utilizada fere diretriz de acessibilidade.
**Ocorrência:** web e mobile
**Recomendação:** barras deveriam ser a mesma cor e recomenda-se utilizar a cor verde para cumprir, amarelo para parcialmente e vermelho quando não cumpre.

- [ ] #303
**Contexto:** Ao selecionar a Área de atuação a estrutura para selecionar é em modal, ao clicar no modal aparecem labels. No mobile não há barra de rolagem para navegar entre as áreas.
**Ocorrência:** web e mobile
**Recomendação:** seleção via menu dropdown.

**Comment by wforte88** [comment]
@lpirola Estes bugs impacta os testes de usabilidade. Podes verificar e nos dar uma estimativa de prazo para resolução?

**Comment by RaniGub** [comment]
Emille vai adicionar alguns novos Bugs encontrados.

**Comment by RaniGub** [comment]
Mapeamento inicial finalizado, algumas issues serão movidas para coluna "UX/UI realizado" após alinhamento entre pares.
