### ISSUE TITLE
Identificação de melhorias | Eventos

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#186]
**Contexto**
Precisamos identificar melhorias de rápida implementação para possibilitar que as funcionalidades mínimas do Mapas tenham uma experiência minimamente eficiente.

_________________________________________________________________________________________________________________

**[Legenda] Níveis de criticidade:**
Alta: está impedindo a navegação do usuário.
Média: impacta consideravelmente a experiência do usuário.
Baixa: não tem grande impacto na experiência do usuário.

  **NÍVEL DE CRITICIDADE: ALTA**

- [ ] #218
**Contexto:** Na tela "Eventos", no quadro "Filtros de eventos" o clique no botão "Limpar todos os filtros" não traz nenhum retorno. Deve limpar todos os previamente filtros selecionados.
**Ocorrência:** desktop e mobile

- [ ] #219
**Contexto:** Na página de edição do evento (tela inicial > eventos > acessar (evento) > editar evento), se incluo um banner e um avatar para o evento, ele não é apresentado (tanto na página de visualização do evento quanto na própria página de edição de eventos).
**Ocorrência:** desktop e mobile

- [ ] #220
**Contexto:** Na página de edição do evento (tela inicial > eventos > acessar (evento) > editar evento), no bloco de "Informações públicas do evento", imagens adicionadas aparecem quebradas na galeria de fotos do evento. Além disso, links inclusos nessa seção não são apresentados ao usuário.
**Ocorrência:** desktop e mobile

- [ ] #221
**Contexto:** Na página do evento, tanto na modal "Contato" quanto na modal "Denúncia", não há um aviso de erro caso o usuário tente enviar o conteúdo sem preencher os campos. Além disso, não há nenhum aviso que relata que o envio foi efetuado, o que leva a acreditar que a mensagem não foi enviada. Se não foi, corrigir situação. Se foi, incluir uma mensagem de sucesso.
**Ocorrência:** desktop e mobile

- [ ] #222
**Contexto:** No bloco de filtros da página de pesquisa, existem opções pré-definidas além da busca por data no calendário ("hoje", "amanhã", "esta semana"...). Estamos em abril e, nessas opções, o mês apresentado para seleção é Maio. O ideal seria que, em um determinado mês, a opção de filtragem rápida por um determinado mês seja do mês vigente.
**Ocorrência:** desktop 

- [ ] #223
**Contexto:** Eventos publicados que contém um avatar não aparecem na lista de eventos. As datas dos eventos, porém, ficam marcadas. 
**Ocorrência:** desktop e mobile

- [ ] #224
**Contexto:** No meu celular, quando acesso o painel de controle, vejo logo os cards "Agentes" e "Oportunidades". Por conhecer a versão desktop, sei que existe a rolagem lateral para revelar os itens "Eventos", "Espaços" e "Projetos". Em um primeiro acesso diretamente no celular, é possível que o usuário não perceba essa possibilidade. A sugestão é adicionar setas que indicam que existe mais conteúdo lateralmente, tal como em "Inscrições recentes" e em "Editados recentemente". 
**Ocorrência:** mobile

- [ ] #225
**Contexto:** No painel de controle, no card de eventos, o usuário tem duas opções: criar um novo evento (clicando no botão "+ criar") ou gerenciar eventos (clicando em qualquer outro local do card). Não há indicação, porém, de que o card é clicável. Na visualização mobile, sem o hover, é possível que esse entendimento não fique claro. Sugiro que o texto "X Eventos" assuma a cor de link ou que seja incluído com novo botão "Gerenciar eventos".
**Ocorrência:** desktop e mobile

- [ ] #226
**Contexto:** Mesmo os eventos que aparecem na visualização por lista na página de eventos não estão constando na visualização por mapa.
**Ocorrência:** desktop e mobile

- [ ] #248
**Contexto:** Embora o título seja auto-descritivo, seria interessante um texto explicativo da seção indicando de maneira breve o que é um evento para a plataforma Mapas. Inserir texto descritivo da seção.
**Ocorrência:** desktop e mobile

- [ ] #227
**Contexto:** Nas telas "Oportunidades", "Agentes", "Espaços" e "Projetos" existe um padrão de ordenação e quantidade de resultados. Se possível, replicar também em "Eventos".
**Ocorrência:** desktop e mobile

**NÍVEL DE CRITICIDADE: MÉDIA**

- [ ] #237
**Contexto:** Na tela "Eventos", quando não existe qualquer evento cadastrado, o usuário não recebe essa informação. Pode induzir o usuário a pensar que o carregamento das informações não foi concluído. Incluir texto: "Não existem eventos cadastrados para os filtros selecionados."
**Ocorrência:** desktop e mobile

- [ ] #228
**Contexto:** Na tela "Eventos", não existe nenhuma indicação de filtro default, o que faz com que o resultado (antes da pesquisa por filtros específicos) seja sempre em branco. Incluir um período default (Para informação: Espírito Santo e Pará utilizam "próximos 30 dias").
**Ocorrência:** desktop e mobile

- [ ] #229
**Contexto:** Na tela mobile de "Eventos", na modal "Filtros de eventos", assim como nas modais dos campos dropdown (tais como "Eventos oficiais" e "Linguagens"), não há um botão "aplicar filtros". Pode levar o usuário a pensar que não existe uma maneira de adicionar os filtros selecionados. Nesse cenário, a descoberta de que os filtros foram aplicados acontece mediante à desistência e consequente clique no ícone de "fechar". Para melhoria na experiência, adicionar botão "aplicar filtros". O resultado deve ser o mesmo do ícone "fechar".
**Ocorrência:** mobile

- [ ] #230
**Contexto:** Na versão desktop da página de busca de eventos, existe um campo "Eventos acontecendo" que, além da possibilidade de seleção de data(s) específica(s), possui também a opção de filtrar por rótulos pré-definidos (hoje, amanhã, esta semana...). Tais rótulos não aparecem na versão mobile. Se possível, incluir.
**Ocorrência:** mobile

- [ ] #231
**Contexto:** Na tela "Eventos", no card do evento cadastrado, as tags de "linguagem cultural" aparecem com o mesmo tratamento de link, mas não são clicáveis. Sugere-se dois possíveis tratamentos: 1) inserir clique, resultando com a filtragem correspondente à tag selecionada; 2) Trocar a cor dos textos das tags para preto.
**Ocorrência:** desktop e mobile

- [ ] #232
**Contexto:** Na página de edição do evento (tela inicial > eventos > acessar (evento) > editar evento), quando tento cadastrar uma nova tag, ocorre um comportamento indesejado no momento da digitação da primeira tag a ser adicionada: a cada novo caractere digitado, acontece um scroll automático para o fim da tela, de forma que o usuário é obrigado a clicar novamente no campo de texto para digitar o próximo caractere. O comportamento se repete a cada digitação de um novo caractere. Corrigir.
**Ocorrência:** desktop

- [ ] #233
**Contexto:** Na página de edição do evento (tela inicial > eventos > acessar (evento) > editar evento), existem diversos campos para a inserção de links ("link para a página ou site do evento", bloco de links de redes sociais, bloco de informações públicas do evento). O sistema não aceita links que não estejam no formato http://www.site.com, mas também não aponta exatamente qual é o erro quando o usuário digita, por exemplo, www.site.com. A correção ideal seria aceitar o link sem o "https://" e incluir automaticamente no caso de uma inclusão desta forma. Uma solução alternativa seria trocar o texto "A url informada é inválida." por "A URL informada é inválida. Informe no formato https://www.site.com" e tente novamente".
**Ocorrência:** desktop e mobile

- [ ] #234
**Contexto:** No bloco "Data, hora e local do evento", podem ser inseridas novas ocorrências (botão "Inserir nova ocorrência) e excluídas ("Excluir"). As ocorrências não podem, porém, ser editadas. Desta forma, para editar, o usuário precisa excluí-la e cadastrá-la novamente. Viabilizar a edição da ocorrência melhoraria significativamente a experiência de um usuário que se depare com essa necessidade.
**Ocorrência:** desktop e mobile

- [ ] #235
**Contexto:** Na página de edição do evento (tela inicial > eventos > acessar (evento) > editar evento), se aplico edição nos campos "Nome do evento" e "Descrição curta" e, antes de salvar, insiro uma nova ocorrência de "Data, hora e local do evento", as edições feitas nos campos "Nome do evento" e "Descrição curta" desaparecem. É preciso corrigir para que o usuário não perca informações inseridas ao longo do processo de edição do evento.
**Ocorrência:** desktop e mobile

- [ ] #238
**Contexto:** No painel de controle é exibido o número de eventos **publicados**. No rótulo, porém, são "X Eventos", desconsiderando eventos em rascunho, arquivados ou excluídos, que também são eventos a serem contabilizados. Para maior clareza do usuário, a sugestão é trocar o rótulo da página inicial do painel de controle para "X Eventos publicados".
**Ocorrência:** desktop e mobile

- [ ] #239
**Contexto:** Espera-se que, na página de edição do evento (tela inicial > eventos > acessar (evento) > editar evento), possam ser feitas todas as edições possíveis relacionadas ao evento em questão. Não há, porém, a opção de adicionar ou excluir selos. Se possível, inserir também nessa página.
**Ocorrência:** desktop e mobile

- [ ] **[EVENTOS]** **_[Hacklab está fazendo]_** Selos não aparecem na apresentação do evento
**Contexto:** Na lista de eventos, para os casos de eventos com selo, não é possível identificar qual o selo (aparece apenas "SELOS (1):, sem especificar qual é o selo. Inserir informação.
**Ocorrência:** desktop e mobile

- [x] #240
**Contexto:** Na página de detalhes do evento, o selo aparece em preto com o fundo cinza, dando a impressão de botão desabilitado. Sugere-se indicar a ilustração do selo com cor de link, para ficar claro que é clicável. Além disso, seria interessante inserir a informação de qual é o selo com o hover.
**Ocorrência:** desktop e mobile

- [ ] **[EVENTOS]** **_[Hacklab está fazendo]_** O evento publicado sem ocorrência não é de fato publicado.
**Contexto:** Excluir botão "Criar e publicar". Ao criar em rascunho, na modal "Evento criado em rascunho!", Trocar texto da modal para: "Para publicar o evento, você deve cadastrar ao menos uma Ocorrência. Você pode completar as informações do seu evento agora ou pode deixar para depois. Para completar e publicar seu novo evento, acesse a área **Rascunhos** em Meus Eventos no **Painel de Controle**. | **Deseja inserir uma ocorrência para o seu Evento?** Você pode inserir agora uma ocorrência do seu evento ou a ocorrência única. (botão "Inserir nova ocorrência") | Botões "Ver evento", "Completar depois", "Completar informações". 
**Ocorrência:** desktop e mobile

**NÍVEL DE CRITICIDADE: BAIXA**

- [ ] #241
**Contexto:** Na tela "Eventos" (versão mobile), a modal "Filtros de eventos" não ocupa a tela inteira. Na tentativa de scroll, é possível ver a tela do fundo scrollando, enquanto a modal de filtros permanece fixa. O ideal seria que a modal ocupasse a totalidade da tela e ações com a tela principal fossem possíveis/visíveis apenas com a modal fechada.
**Ocorrência:** mobile

- [ ] #242
**Contexto:** Encontrei eventos com o campo entrada preenchido como "GRATUITO" e "R$ 0,00". Visando a padronização, é possível impedir o usuário de colocar o valor "R$ 0,00" caso ele informe que o evento não é gratuito? 
**Ocorrência:** desktop e mobile

- [ ] #243
**Contexto:** Na página de edição do evento (tela inicial > eventos > acessar (evento) > editar evento), no cadastro de tag, o campo de preenchimento de uma nova tag aparece sobreposto ao local em que ficam registradas as tags cadastradas. Esse campo não desaparece quando clico no botão "+" para inserir uma nova tag, de forma que, por vezes, esconde o feedback da ação (que é o registro de uma nova tag). Sugere-se fechar o campo quando feita a inclusão de cada nova tag, de forma que sempre fique visível para o usuário o aparecimento da tag cadastrada. Para nova inserção, o usuário deve clicar novamente em "adicionar nova".
**Ocorrência:** desktop

- [ ] #249
**Contexto:** Na tela "Eventos", no bloco de filtros, existe uma opção "Eventos oficiais", mas não há uma especificação do que define um evento oficial. A sugestão é que, no ícone do check, se inclua uma tooltip com o seguinte texto: "(Alinhar com Narrativas)".
**Ocorrência:** desktop e mobile

- [ ] #244
**Contexto:** Na página de edição do evento (tela inicial > eventos > acessar (evento) > editar evento), quando insiro/excluo o registro de uma ocorrência, o sistema exibe um aviso "Entidade salva/removida". Se estamos tratando como "Ocorrência", o ideal seria que o aviso fosse ajustado para "Ocorrência salva/removida".
**Ocorrência:** desktop e mobile

- [ ] #255
**Contexto:** No Painel de controle, versão mobile, existem setas que indicam rolagem lateral de informações. Essas setas, porém, aparecem também quando não há informações suficientes para que seja possível uma rolagem lateral. Sugiro que, em casos como esse, elas não apareçam ou apareçam desabilitadas (ícone de seta cinza ao invés do link esverdeado)
**Ocorrência:** mobile

**Comment by emillecatarine** [comment]
**[Legenda] Níveis de prioridade:**
Alta: está impedindo a navegação do usuário.
Média: impacta consideravelmente a experiência do usuário.
Baixa: não tem grande impacto na experiência do usuário.


  **NÍVEL DE PRIORIDADE: ALTA**
- [ ] [desktop/mobile] No quadro "Filtros de eventos" o botão "Limpar todos os filtros" não funciona.
- [ ] 

**NÍVEL DE PRIORIDADE: MÉDIA**

- [ ] [desktop/mobile] Não existe nenhum resultado e o usuário não recebe essa informação. Incluir texto: "Não existem eventos cadastrados no período selecionado."
- [ ] [desktop/mobile] Não existe nenhuma indicação do período que está sendo filtrado. Incluir um período default (Espírito Santo e Pará utilizam "próximos 30 dias").
- [ ] [mobile] No quadro "Filtros de eventos", quando um filtro dropdown (tais como "Eventos oficiais" e "Linguagens", abre uma nova tela para a seleção. Não há um botão "adicionar filtros", o que me faz pensar que não existe uma maneira de adicionar os filtros selecionados. Quando desisto e clico no botão "fechar", percebo que foram acrescentados. Para melhoria na experiência, adicionar botão "adicionar filtros".

**NÍVEL DE PRIORIDADE: BAIXA**
- [ ] [mobile] A modal "Filtros de eventos" não ocupa a tela inteira. Deixa a impressão de que o scroll é possível mas, no ato da tentativa, é possível ver a tela do fundo scrollando. O ideal seria que a modal ocupasse a totalidade da tela.

**Comment by RaniGub** [comment]
Mapeamento inicial finalizado.

**Comment by emillecatarine** [comment]
Primeira onda de identificação de melhorias de [EVENTOS] finalizada.
