### ISSUE TITLE
Identificação de melhorias | Espaços

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#187]
**Contexto**
Precisamos identificar melhorias de rápida implementação para possibilitar que as funcionalidades mínimas do Mapas tenham uma experiência minimamente eficiente.

**[Legenda] Níveis de criticidade:**
Alta: está impedindo a navegação do usuário.
Média: impacta consideravelmente a experiência do usuário.
Baixa: não tem grande impacto na experiência do usuário.

  **NÍVEL DE CRITICIDADE: ALTA**

- [ ] #280
**Contexto:** Embora o título seja auto-descritivo, seria interessante um texto explicativo da seção indicando de maneira breve o que é um espaço para a plataforma Mapas. 
**Ocorrência:** desktop e mobile
**Recomendação:** Inserir texto descritivo da seção: "(Alinhar com narrativas)".

- [ ] #256
**Contexto:** Na página de detalhes do Espaço, tanto na modal "Contato" quanto na modal "Denúncia", não há um aviso de erro caso o usuário tente enviar o conteúdo sem preencher os campos. Além disso, não há nenhum aviso que relata que o envio foi efetuado, o que leva a acreditar que a mensagem não foi enviada.
**Ocorrência:** desktop e mobile
**Recomendação:**  Se as mensagens não foram enviadas, corrigir situação. Se foram, incluir uma mensagem de sucesso.

- [ ] #257
**Contexto:** Na página de edição do espaço (tela inicial > eventos > acessar (espaço) > editar espaço), se incluo um banner e/ou um avatar, eles não são apresentados (tanto na página de visualização do espaço quanto na própria página de edição de espaços).
**Ocorrência:** desktop e mobile
**Recomendação:** Corrigir erro.

- [ ] #258
**Contexto:** Na página de edição do espaço (tela inicial > espaço > acessar (espaço) > editar espaço), no bloco "Informações públicas do espaço", imagens adicionadas aparecem quebradas na galeria de fotos do espaço. Além disso, links inclusos nessa seção não são apresentados ao usuário.
**Ocorrência:** desktop e mobile
**Recomendação:** Corrigir erro para que a imagem e os links cadastrados no bloco "Informações públicas do espaço" fiquem visíveis na página de detalhes do Espaço.

- [ ] #259
**Contexto:** Cadastrei um Espaço chamado Ginásio Nilson Nelson, em Brasília. CEP: 70070-705. Testei no Google Maps, e aparece em Brasília, no local onde o Espaço de fato está. No mapa da plataforma, o Espaço não aparece no local correto. No mapa de edição do Espaço, aparece no Oceano Atlântico. No mapa da busca de espaços, não aparece.
**Ocorrência:** desktop e mobile
**Recomendação:** Corrigir bug.

- [ ] #260
**Contexto:** Na visualização dos Espaços pelo mapa, existe a opção de clicar no Espaço para visualizar uma tootltip com informações. A tooltip não está apresentando informação alguma.
**Ocorrência:** desktop e mobile
**Recomendação:** Corrigir bug.

**NÍVEL DE CRITICIDADE: MÉDIA**

- [ ] #261
**Contexto:** Na tela “Espaços”, no card do espaço cadastrado, as tags de “TIPO” e “ÁREAS DE ATUAÇÃO” aparecem com o mesmo tratamento de link, mas não são clicáveis. 
**Ocorrência:** desktop e mobile
**Recomendação:** Sugere-se dois possíveis tratamentos: 1) inserir clique, resultando com a filtragem correspondente à tag selecionada; 2) Trocar a cor dos textos das tags para preto.

- [ ] #262
**Contexto:** Na página de edição do espaço (tela inicial > eventos > acessar (espaço) > editar espaço), existem diversos campos para a inserção de links ("link para a página ou site do espaço”, bloco de links de redes sociais, bloco “mais informações públicas”). O sistema não aceita links que não estejam no formato http://www.site.com/, mas também não aponta exatamente qual é o erro quando o usuário digita, por exemplo, [www.site.com](http://www.site.com/). 
**Ocorrência:** desktop e mobile
**Recomendação:** A correção ideal seria aceitar o link sem o "https://" e incluir automaticamente no caso de uma inclusão desta forma. Uma solução alternativa seria trocar o texto "A url informada é inválida." por "A URL informada é inválida. Informe no formato https://www.site.com/" e tente novamente".

- [ ] #263
**Contexto:** Na página de edição do Espaço (tela inicial > espaços > acessar (espaço) > editar espaço), quando tento cadastrar uma nova tag, ocorre um comportamento indesejado no momento da digitação da primeira tag a ser adicionada: a cada novo caractere digitado, acontece um scroll automático para o fim da tela, de forma que o usuário é obrigado a clicar novamente no campo de texto para digitar o próximo caractere. O comportamento se repete a cada digitação de um novo caractere. 
**Ocorrência:** desktop
**Recomendação:** Corrigir bug.

- [ ] #269
**Contexto:** Quando acesso a página de busca dos Espaços, tenho acesso ao card de cada espaço com Avatar, Nome do Espaço, Tipo, Endereço, Descrição curta, Área de Atuação e Tags. Já na página de detalhes do Espaço, tenho acesso à todas essas informações, mas não do Endereço.
**Ocorrência:** desktop e mobile
**Recomendação:** Incluir na página de detalhes do Espaço as informações de Endereço e, se possível, o mapa.

**NÍVEL DE CRITICIDADE: BAIXA**

- [ ] #281
**Contexto:** Na tela “Espaços”, no bloco de filtros, existe uma opção “Espaços oficiais", mas não há uma especificação do que define um espaço oficial.
**Ocorrência:** desktop e mobile
**Recomendação:** No ícone do check, incluir uma tooltip com o seguinte texto: "(Alinhar com narrativas)".

- [ ] #264
**Contexto:** Na página de “Espaço”, o campo “Tipo” tem um tamanho e peso de fonte. O campo “Onde” tem outro tamanho e peso de fonte. Os demais campos tem um terceiro tamanho e peso de fonte. 
**Ocorrência:** desktop e mobile
**Recomendação:** Padronizar para dois pesos e um tamanho (aplicar mesma regra para todos os cards de todas as seções do sistema).

- [ ] #265
**Contexto:** Na página de detalhes do Espaço, a quebra de linha da descrição do Espaço está cortando a palavra (por exemplo, na minha tela cortou Dis-trito). 
**Ocorrência:** desktop e mobile
**Recomendação:** É preciso ajustar para que palavras que não caibam inteira em uma linha sejam apresentadas completas na linha seguinte.

- [ ] #266
**Contexto:** Na página de detalhes do Espaço, o link do espaço está sendo apresentado em preto. Mesmo com o ícone de link ao lado, ficaria mais claro se o próprio link tivesse a cor de link aplicada.
**Ocorrência:** desktop e mobile
**Recomendação:** Aplicar cor de link no link do espaço (corresponde ao preenchimento do campo “Link para página ou site do espaço”).

- [ ] #267
**Contexto:** Na tela de resultados de “Espaços”, o texto “X Espaços encontrados” com o fundo branco faz parecer que é um botão. 
**Ocorrência:** desktop
**Recomendação:** Retirar o fundo branco.

- [ ] #268
**Contexto:** Na versão mobile da tela de resultados de “Espaços”, o dropdown de ordenação e o indicativo de resultados encontrados para os filtros selecionados não aparecem.
**Ocorrência:** desktop
**Recomendação:** Inserir dropdown de ordenação e indicativo de resultados também na versão mobile.

- [ ] #270
**Contexto:** Na modal de "Criar Espaço", no campo "Área de atuação", quando faço uma pesquisa textual por uma área, o sistema filtra o espaço pesquisado. Quando seleciono o(s) espaço(s) e clico no botão "Confirmar", o sistema fecha a modal e adiciona o(s) filtro(s) selecionado(s). Se opto por abrir novamente a modal, ela segue com o texto de um filtro que já fiz.
**Ocorrência:** desktop e mobile
**Recomendação:** Zerar o campo de pesquisa quando o usuário clicar em "Confirmar". 

- [ ] #273
**Contexto:** Entrei no sistema, fiz o login, comecei a criar um espaço. Não terminei, quando voltei para terminar, o login já havia expirado mas não percebi. Tentei cadastrar o evento, não obtive sucesso mas também não obtive nenhuma mensagem de erro. Cliquei no botão de criar e publicar, nada aconteceu. Cliquei no botão de manter em rascunho, também nada aconteceu.
**Ocorrência:** desktop e mobile
**Recomendação:** Adicionar aviso de erro quando o usuário tentar criar um evento sem o login ativo.

- [ ] #274
**Contexto:** Na página de edição do Espaço (tela inicial > eventos > acessar (espaço) > editar espaço), os campos obrigatórios ficam marcados com o texto “*obrigatório* em vermelho, logo à frente do título do campo de preenchimento. Esse tratamento (texto vermelho próximo ao campo de preenchimento) se assemelha ao tratamento de erro. Ao preencher o formulário e tentar submeter com um campo incorreto, meu primeiro pensamento foi de que haviam erro nesses três campos. Com o scroll, percebi que o erro estava em outro campo, com um tratamento muito parecido.
**Ocorrência:** desktop e mobile
**Recomendação:** Indicar obrigatoriedade apenas com um asterisco vermelho ao lado dos campos. Embaixo do título “Informações de Apresentação”, trocar texto para: “Os campos marcados com (asterisco vermelho) são de preenchimento obrigatório. Os dados inseridos abaixo serão exibidos para todos os usuários.”. Aplicar regra para todos os formulários do sistema.

- [ ] #276
**Contexto:** Na página de edição do Espaço, o usuário tem a opção de incluir um "Link para página ou site do espaço". Esse link é apresentado na íntegra na página do Espaço. Esse link, porém, pode ser muito longo, afetando a estética da página.
**Ocorrência:** desktop e mobile
**Recomendação:** Dar ao usuário a opção de incluir um texto que mascare o link. Desta forma, seria apresentado o texto indicado com o clique direcionando ao link informado.

- [ ] #278
**Contexto:** Na página Espaços, quando abro a modal "Criar Espaço", o dropdown "Selecione o tipo do espaço" não está ordenado alfabeticamente. Por serem muitas opções, facilitaria para o usuário se a ordem alfabética (A–Z) fosse adotada.
**Ocorrência:** desktop e mobile
**Recomendação:** Ordenar itens do dropdown "Selecione o tipo do espaço" alfabeticamente (A–Z).

- [ ] #279
**Contexto:** Quando cadastro um espaço que possui um supra espaço vinculado, o supra espaço em questão aparece na tela de de detalhes do determinado Espaço em verde e negrito, apesar de não ser clicável. 
**Ocorrência:** desktop e mobile
**Recomendação:** Como necessariamente existe uma tela de detalhes para o supra espaço vinculado, sugiro adicionar link no texto para que o usuário possa, através do link, acessar a página de detalhes do supra espaço.

**Comment by emillecatarine** [comment]
Primeira onda de identificação de melhorias de [ESPAÇOS] finalizada
