### ISSUE TITLE
[PROD 3.4] 1 (um) Painel de indicadores público, baseado em arquitetura de dados  que contenha os indicadores estratégicos do ecossistema

### ISSUE THREAD

**Issue by thaisbtoscano** [LabCDBr/gestao#19]
### Escopo (em construção)

- Painel publicado no site da Rede Mapas com visualização de dados selecionados sobre as soluções digitais mapeadas.
- Código fonte do painel publicado em repositório público.

### Observações
Refinar proposta de formulário para coleta de dados e alimentação do painel.

**Comment by wforte88** [comment]
Produto substituído pelo #620
