### ISSUE TITLE
Integrar feed do site ao Mastodon / Fediverso

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#196]
Instalar plugin no wordpress para integrar feed do site ao Mastodon / Fediverso para que o conteúdo do site seja publicado no fediverso.

**Comment by marlioesmeraldo** [comment]
Perfil criado:
https://mastodon.social/@mapas

**Comment by diegonrojas** [comment]
Foi feita uma tentativa de integrar o plugin: https://wordpress.org/plugins/activitypub/, mas ainda não foi bem sucedida

**Comment by diegonrojas** [comment]
Foi feito uma tentativa de integração do feed RSS com a nossa página do mastodon.social, mas ainda num deu certo.

**Comment by diegonrojas** [comment]
A integração a partir do Mastofeed se demonstrou funcional apesar do atraso para a publicação no Fediverso.

![Image](https://github.com/LabCDBr/gestao/assets/154905066/27c6342c-4f1d-416f-b171-d8c4a93a5a50)

Estamos presentes no Fediverso em: https://mastodon.social/@mapas

**Comment by marlioesmeraldo** [comment]
Revisão ok.
