### ISSUE TITLE
Agendamento da 1ª reunião na Plantaformas e Jitsi

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#199]
Criar uma reunião na Plantaformas, na página da Rede de Cultura Digital e criar um link no Meet.jit.si para realizar o encontro

**Comment by diegonrojas** [comment]
Opa, foi criada a reunião na Plantaformas:
https://plantaformas.org/assemblies/culturadigitalbrasileira/f/47/meetings/262

E também foi criado um endereço fixo no Jitsi para as reuniões em conjunto com a Livia do Hacklab:
https://meet.jit.si/MapasCulturais

**Comment by marlioesmeraldo** [comment]
O texto está ótimo. Só sugiro incluir:
- Objetivo da reunião
- Pautas da reunião
