### ISSUE TITLE
Roteirização da 1ª Reunião de Escuta

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#200]
Definição e redação de roteiro da 1ª Reunião de Escuta da comunidade.

Documento do roteiro:
https://docs.google.com/document/d/1ZA5w2ixbXKEiPoXWz1Af5stLHP2x5wgInxEwfiw5Txo/edit?usp=sharing

**Comment by diegonrojas** [comment]
Roteiro foi seguido e temos um regsitro e um relato na Plantaformas: 
https://plantaformas.org/assemblies/culturadigitalbrasileira/f/47/meetings/262
https://bloco.cosmo.tec.br/p/plantaformas-MEET-2024-04-262-89b1a389bcefbbc32088
