### ISSUE TITLE
Divulgação em Sites em Mídias Sociais da 2ª Reunião de Governança

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#202]
Realizar ampla convocação da comunidade para a 2ª Reunião de Escuta.

**Comment by diegonrojas** [comment]
Gostaria de saber se essa issue tem relação com a #140, me pareceu algo meio duplicado. @wforte88 @marlioesmeraldo

**Comment by marlioesmeraldo** [comment]
Sim @diegonrojas. São etapas do épico #137 .

**Comment by diegonrojas** [comment]
Realizamos a divulgação no seguinte canais

**Redes Sociais:**
Instagram - OK
Mastodon - OK
Site - OK

**Grupos WhatsApp:**
GT Políticas - Ninguém da Narrativas está no grupo, o que nos impossibilitou de divulgar por lá.
GT Sustentabilidade - OK
Cadastro Cultural Nacional - OK

**Grupos Telegram:**
GT Tecnologias - OK
Mapas Culturais - OK
Rede Mapas - OK

**Comment by diegonrojas** [comment]
Registrando o layout que foi criado para a chamada da reunião:


![Image](https://github.com/LabCDBr/gestao/assets/154905066/032a2d5e-fb43-4acf-83df-382523473928)
