### ISSUE TITLE
Realizar 1ª Reunião de Escuta em Comunidade

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#203]
A primeira reunião de escuta/colaboração em comunidade será realizada no dia 24/04, às 15:30, em uma sala do Jitsi, tem como pauta prioritária o compartilhamento da nova documentação desenvolvida pela equipe de tecnologia do MinC, oportunizando um primeiro momento de apresentação da equipe e do TED Mapas. Nas reuniões seguintes, a governança e o relacionamento em comunidade serão aprofundados.

**Comment by Narapessoa** [comment]
Nara:
A pedido do @uira a reunião do dia 17/04 foi suspensa para que se possa fazer alinhamentos de objetivos, abordagens e expectativas entre MINC e Comunidade.

**Comment by Narapessoa** [comment]
Segue convite enviado pela comunidade:

Nesta quarta-feira, dia 24/04, das 15h30 às 17h00 , a comunidade Mapas Culturais estará reunida para conversar sobre “documentações”, abordando aspectos como padronização, organização e produção de manuais técnicos e para o público final.

✅ O encontro foi convocado pela equipe de tecnologia do Ministério da Cultura (MinC) para a apresentação da documentação sobre jornadas e arquitetura que elaboraram no decorrer do processo de atualização.

📍Também está na pauta uma breve apresentação da memória do Mapas e da comunidade, bem como o projeto “Qualificação do Ecossistema de Soluções Digitais para Mapeamento e Gestão Cultural” realizado pelo MINC e Universidade do Federal do Paraná (UFPR).

✅ Para quem quiser acessar a documentação, ela já está disponível no link: https://github.com/mapasculturais/mapasculturais/issues/3158

O evento foi criado na Plantaformas. Para participar da reunião, visualizar o link da chamada e o relato é necessário (e simples) estar logada: https://plantaformas.org/assemb

📍📍Segue link da reunião: http://meet.jit.si/MapasCulturais

Segue card:

![Image](https://github.com/LabCDBr/gestao/assets/155664490/8389d857-ab2c-443f-9e66-c8d87299922b)

**Comment by Narapessoa** [comment]
Encaminhamentos da reunião do dia 24/04/24.

** Marcado encontro no dia 02/05/24, às 10h, para:** 

- Compartilhar os eixos centrais do plano de governança
- Dialogar sobre a  criação de fluxo para a atualização do Software Mapas
- Acordar um calendário/fluxo de reuniões da comunidade que tem como objetivo principal organização da comunidade.

**Comment by diegonrojas** [comment]
A documentação foi publicada hoje em um repositório do LabCD
Documento Manual do Usuário Mapas Culturais v7:
https://labcdbr.github.io/docs/Manuais/Mapas%20Culturais%20Manual%20de%20Usuario.pdf

Documento de Arquitetura de Software:
https://labcdbr.github.io/docs/Arquitetura/MINC_MAPASv7_DAS.pdf

Análise detalhada de banco de Dados:
https://labcdbr.github.io/docs/Banco%20de%20Dados/analise-detalhada/index.html

Diagramas Simples do Banco de Dados:
https://labcdbr.github.io/docs/Banco%20de%20Dados/diagramas-simples/mapas7%20-%20public.png
https://labcdbr.github.io/docs/Banco%20de%20Dados/diagramas-simples/mapas7%20-%20tiger.png
https://labcdbr.github.io/docs/Banco%20de%20Dados/diagramas-simples/mapas7%20-%20topology.png

Documentação das funcionalidades Mapas Culturais:
https://labcdbr.github.io/docs/Funcionalidades/html/index.html#/feature/00_Documento_de_Vis%C3%A3o_MINC_MAPAS_7.0_Documento_de_visao

**Comment by Narapessoa** [comment]
Falta acrescentar relatoria da primeira reunião.
