### ISSUE TITLE
Realizar 2ª Reunião de Escuta da Comunidade

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#205]
A 2ª Reunião de Escuta em Comunidade, e a primeira para tratar especificamente de Governança, tem como objetivo apresentar os eixos principais do plano de governança, definição de um calendário de reuniões até junho de 2024, bem como organização e responsabilidades dos grupos de trabalho e definição de fluxos para atualização contínua das documentações e do software.

**Comment by Narapessoa** [comment]
Essa reunião foi cancela @marlioesmeraldo

**Comment by Narapessoa** [comment]
A segunda reunião de governança da Rede Mapas será no dia 08/05/24, das 10h às 12h.

**Comment by Narapessoa** [comment]
06/05/24 reunião com @marlioesmeraldo @diegonrojas sobre a reunião de governança do dia 02/05/24.

1. Diego vai aprovar com o @uira Uirá o card de divulgação e a estrutura para a transmissão da reunião, pois a TV Tainá, conforme sugeriu Uirá, nesse momento, talvez não seja o melhor caminho.
2. Alinhamento com a equipe do roteiro para condução do encontro. 
3. Definição dos papéis para as reuniões: Nara, vai atuar na mediação, Márlio irá ficar com a estrutura de transmissão, Diego irá fazer a relatoria.
4. Definição dos papéis para os GTs: Nara, Marlio e Diego ficam com a mediação dos GTs, respectivamente:

**Comment by Narapessoa** [comment]
![Image](https://github.com/LabCDBr/gestao/assets/155664490/9dcc4a33-f2ba-45b2-9710-4fa4bbfb52ce)

**Comment by Narapessoa** [comment]
Segue Link do segundo encontro
