### ISSUE TITLE
Roteiro e instrumentos | Mapeamento de Jornadas

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#206]
**Contexto**

Desenvolvendo documento de Roteiro de Pesquisa para mapeamento da jornada.

Agente cultural:
https://fuchsia-existence-452.notion.site/Roteiro-de-Pesquisa-para-Mapeamento-da-Jornada-Andr-2a8d4516d1054118ae8e311962765c60

**Comment by drabelodesign** [comment]
Link para acesso ao quadro com os roteiros de pesquisa que serão realizados com o André e Vinicius.

https://www.notion.so/UX-Design-9f920c30c4014a449cd42a4c59a6efac?pvs=4

**Comment by RaniGub** [comment]
Tarefa pareada e finalizada. @drabelodesign por gentileza, depois insira o link do Figma do Template da Jornada.

**Comment by drabelodesign** [comment]
Link do Template v.01
https://www.figma.com/file/22Vp8T2JQ3tWOYTZEZeBrY/Jornada-Andr%C3%A9-Secult%2FCE?type=whiteboard&node-id=0%3A1&t=PpamMXrMdqojucM5-1
