### ISSUE TITLE
[EVENTOS] Selos com fundo cinza traz a impressão de desabilitado

### ISSUE THREAD

**Issue by emillecatarine** [LabCDBr/gestao#240]
**Contexto:** Na página de detalhes do evento, o selo aparece em preto com o fundo cinza, dando a impressão de botão desabilitado. Sugere-se indicar a ilustração do selo com cor de link, para ficar claro que é clicável. Além disso, seria interessante inserir a informação de qual é o selo com o hover.
**Ocorrência:** desktop e mobile

**Comment by RaniGub** [comment]
Revisão UX/UI realizada, issue será fechada.
