### ISSUE TITLE
Design System | Definições

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#246]
**Contexto**
Estamos realizando alguns alinhamento para definirmos a jornada de estruturação de um Design System para o Mapas.

**Informações complementares**

**Comment by lpirola** [comment]
Lista de componentes vue:

- mc-modal
- mc-tab
- mc-entity
- mc-breadcrumb
- mc-stepper
- mc-entities
- mc-map
- mc-card
- mc-share-links
- mc-map-marker
- mc-status
- mc-summary-evaluate
- mc-notification
- mc-tabs
- mc-icon
- mc-link
- mc-avatar
- mc-container
- mc-accordion
- mc-summary-agent-info
- mc-summary-spaces
- mc-multiselect
- mc-debug
- mc-select
- mc-header-menu-user
- mc-summary-agent-info
- mc-currency-input
- mc-stepper-vertical
- mc-confirm-button
- mc-title
- mc-map-card
- mc-tag-list
- mc-popover
- mc-loading
- mc-alert
- mc-messages
- mc-header-menu
- mc-relation-card
- mc-collapse
- mc-summary-project
- mc-file
- mc-summary-agent

**Comment by RaniGub** [comment]
Reunião de 16/04.
Lucas e Victor vão estudar as possibilidades de Design Systems prontos para tomarmos uma decisão, considerando os critérios:
- Esforço de implementação no software
- Acessibilidade
- Responsividade
- Perfomrnace
- Recebe atualizações
- Tem UI Kit Design
- Tem Guia de Estilos

Após isso, o time de design faz uma validação geral de interface.
Design Systems considerados até agora:
https://vuetifyjs.com/
https://www.radix-ui.com/

**Comment by vicmagpac** [comment]
### Critérios analisados para o vuetify:

A seguir os principais critérios levados em consideração para o uso do vuetify.

- Componentes abrangentes: Vuetify oferece uma grande variedade de componentes prontos para uso,  desde elementos básicos como botões e formulários até componentes mais avançados como gráficos e calendários. 

- Material Design: Vuetify é uma implementação do Material Design, um conjunto de diretrizes de design criado pelo Google. 

- Customização flexível: Apesar de seguir as diretrizes do Material Design, Vuetify permite uma personalização extensiva dos componentes. 

- Integração com Vue.js: Vuetify é construído especificamente para o Vue.js, o que significa que ele se integra ao mapa da saúde v7, pois o mesmo usa o vue. (Necessário avaliar as mudanças dos 170 componentes criados por padrão na V7. Ou seja, refazer todo o front end.)

- Documentação abrangente: Vuetify oferece uma documentação completa e bem organizada, incluindo exemplos de código e guias de uso para cada componente. Isso torna mais fácil e encontrar soluções para problemas comuns durante o desenvolvimento.

- Ativo ecossistema e comunidade: Vuetify possui uma comunidade ativa de desenvolvedores e uma variedade de recursos adicionais, como temas, plugins e extensões. 

- Manutenção regular e atualizações:  biblioteca bem mantida, com atualizações regulares e correções de bugs. 


### Pontos negativos que devem ser especificados:

Os pontos negativos a seguir pode ser aplicado para qualquer ferramenta.

- Complexidade excessiva: Para projetos simples ou pequenos, a extensa gama de componentes e opções de personalização do Vuetify pode parecer um exagero. Isso pode adicionar uma camada de complexidade desnecessária ao projeto.

- Tamanho do pacote: O Vuetify inclui uma grande variedade de recursos e componentes, o que pode resultar em um tamanho de pacote maior do que outras bibliotecas mais leves. Isso pode afetar o tempo de carregamento da aplicação, especialmente em conexões de internet mais lentas.

- Curva de aprendizado: Para iniciantes em Vue.js ou desenvolvedores que não estão familiarizados com o Material Design, a curva de aprendizado do Vuetify pode ser íngreme. A abundância de opções e a complexidade dos componentes podem tornar a familiarização com a biblioteca um pouco mais difícil.

- Personalização limitada em alguns casos: Embora o Vuetify permita uma grande personalização dos componentes, em alguns casos pode ser difícil alcançar certos designs personalizados sem modificar diretamente o código-fonte dos componentes, o que pode complicar atualizações futuras.

- Dependência de uma única estética: Fortemente baseado no Material Design, o que pode limitar a flexibilidade estética para projetos que requerem uma aparência diferente ou que desejam se afastar do design padrão do Google.

- Problemas de compatibilidade: Como em qualquer biblioteca, podem surgir problemas de compatibilidade com outras bibliotecas ou frameworks que você esteja usando em seu projeto.

**Comment by vicmagpac** [comment]
Encaminhamentos 17/04/2024:

- [ ] Criar planilha com as principais libs ui para o mapa com os critérios
- [ ] Critérios Vuetify - https://github.com/vuetifyjs/vuetify
- [ ] Critérios Radix UI - https://github.com/radix-vue/radix-vue
- [ ] Critérios primevue - https://github.com/primefaces/primevue

**Comment by vicmagpac** [comment]
Link da planilha de análise das Libs UI: https://docs.google.com/spreadsheets/d/17xB5Z5fwtJRiK_s0vL4EqzYjcuAvITT5AbGI1riz4wg/edit?usp=sharing

**Comment by RaniGub** [comment]
Bom dia @lpirola e @vicmagpac tem previsão para o movimento de discussão sobre essa issue com a comunidade? Precisamos dessas definições para entregar para o time de tecnologias as issues com o protótipo desenhado.

**Comment by vicmagpac** [comment]
@RaniGub fizemos uma reunião hoje dia 24/04/2024 as 11h para discutir sobre o assunto.
Encaminhamentos sobre a reunião:

- Possivelmente existe o figma do mapa v7, @diegonrojas está realizando o processo de comunicação junto a equipe para disponibilizar o acesso ao figma para análise
- Criar issue no mapasculturais sobre atividade para análise colaborativa sobre o design system do mapa v7, a issue está criada em https://github.com/mapasculturais/mapasculturais/issues/3167

**Comment by lpirola** [comment]
@vicmagpac @diegonrojas esses links? 

- https://www.figma.com/file/Mh2r7G3zzMr529nZoVKOdg/M%C3%B3dulo-de-BI---Mapas-Culturais?type=design&node-id=0-1&mode=design&t=6itGnaSSfdxRTEGn-0
- https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=1307-34622&mode=design&t=lcRWZJmSN536D34r-0

**Comment by vicmagpac** [comment]
> [@vicmagpac](https://github.com/vicmagpac) [@diegonrojas](https://github.com/diegonrojas) esses links?
> 
> * https://www.figma.com/file/Mh2r7G3zzMr529nZoVKOdg/M%C3%B3dulo-de-BI---Mapas-Culturais?type=design&node-id=0-1&mode=design&t=6itGnaSSfdxRTEGn-0
> * https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=1307-34622&mode=design&t=lcRWZJmSN536D34r-0

Sim, esse figma. Obrigado Lucas.

@RaniGub você acha que baseado no figma acima conseguimos dar prosseguimento nas definições de design system?

**Comment by RaniGub** [comment]
> > [@vicmagpac](https://github.com/vicmagpac) [@diegonrojas](https://github.com/diegonrojas) esses links?
> > 
> > * https://www.figma.com/file/Mh2r7G3zzMr529nZoVKOdg/M%C3%B3dulo-de-BI---Mapas-Culturais?type=design&node-id=0-1&mode=design&t=6itGnaSSfdxRTEGn-0
> > * https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=1307-34622&mode=design&t=lcRWZJmSN536D34r-0
> 
> Sim, esse figma. Obrigado Lucas.
> 
> @RaniGub você acha que baseado no figma acima conseguimos dar prosseguimento nas definições de design system?

Oi @vicmagpac, conversando com o Uirá na semana passada entendemos que as telas serão prototipadas apoiadas nos elementos da #348. Aí seguimos com o movimento do Design System ideal para ser implementado em um arquivo modelo de jornada.

**Comment by vicmagpac** [comment]
> > > [@vicmagpac](https://github.com/vicmagpac) [@diegonrojas](https://github.com/diegonrojas) esses links?
> > > 
> > > * https://www.figma.com/file/Mh2r7G3zzMr529nZoVKOdg/M%C3%B3dulo-de-BI---Mapas-Culturais?type=design&node-id=0-1&mode=design&t=6itGnaSSfdxRTEGn-0
> > > * https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-FINAIS?type=design&node-id=1307-34622&mode=design&t=lcRWZJmSN536D34r-0
> > 
> > 
> > Sim, esse figma. Obrigado Lucas.
> > @RaniGub você acha que baseado no figma acima conseguimos dar prosseguimento nas definições de design system?
> 
> Oi @vicmagpac, conversando com o Uirá na semana passada entendemos que as telas serão prototipadas apoiadas nos elementos da #348. Aí seguimos com o movimento do Design System ideal para ser implementado em um arquivo modelo de jornada.

@RaniGub existe alguma pendência desse card para que possamos finalizar?

**Comment by RaniGub** [comment]
Oi @vicmagpac, acredito que não. Os parâmetros e componentes estão aí, agora é evoluir a discussão com a comunidade para entender qual caminho seguir. @emillecatarine se você conseguir ver alguma coisa extra, comente aqui ou dê o sinal para o Victor fechar ;)

**Comment by lpirola** [comment]
#348

**Comment by vicmagpac** [comment]
Baseado no alinhamento da equipe, verificamos que a task não será priorizada para IMPLEMENTAÇÃO no momento. Especificações foram apresentadas no tocante a design system já existente ou novos, levantada no documento https://docs.google.com/spreadsheets/d/17xB5Z5fwtJRiK_s0vL4EqzYjcuAvITT5AbGI1riz4wg/edit.

**Comment by lpirola** [comment]
O diagnóstico foi que adotar um design system a partir dos componentes existentes no código e no figma. Ainda é longe do ideal mas contempla uma mínima organização
