### ISSUE TITLE
Criar texto para o formulário de mapeamento

### ISSUE THREAD

**Issue by Narapessoa** [LabCDBr/gestao#247]
No Link abaixo está o texto e as perguntas que irão compor o formulário para mapeamento da comunidade Mapas.
Submeto o texto para contribuições e validação 

@marlioesmeraldo @diegonrojas @uira fiquem à vontade para sugerir, incluir ou mudar pontos que acharem necessários.
(https://docs.google.com/document/d/1MAljewIk4KRI2PO15ETTV941vDq_SCTd/edit?usp=share_link&ouid=100444666479186316560&rtpof=true&sd=true)

**Comment by marlioesmeraldo** [comment]
Contribuições adicionadas ao documento.

**Comment by Narapessoa** [comment]
A pedido do @uira agendei reunião com @RaniGub para o dia 07/05, ás 11:30. 
Objetivo: orientar e apoiar a execução do mapeamento de jornada e relacionamento da comunidade

**Comment by Narapessoa** [comment]
Reunião com o @RaniGub em 07/05/24

Pauta: apoio a execução do mapeamento de jornada e relacionamento da comunidade

Pontos abordados:
- Rani pensa que o mapeamento da comunidade e a construção de um fluxo de relacionamento (que pode se dividir em uma série de jornadas) são coisas diferentes que podem andar juntos e em paralelo.
- Deu orientações sobre o mapeamento em 4 passos: 1. Identificação da pessoa, 2. Definição do canal de comunicação que vou acessá-la, envio do formulário que estará no Mapas, 4. Como trataremos esses dados (a sugestão segue o que já está no épico que trata do mapeamento.
- A identificação dos atores é importante para entender a jornada de relacionamento.


Encaminhamentos: 
1. Enviar link do épico para análise 
2. Solicitar ao @diegonrojas que crie no Figma uma sugestão de  fluxo de relacionamento com a comunidade (o fluxo podem ter várias jornadas a partir. Exemplo: Quando um Instituto quiser conversar com o MInc ou com uma Secretaria de Cultura de um Estado, qual canal ele acessa, com quem fala?, Se um ente quiser ativar um evento, o que ele vai fazer?
3. Após criação de sugestão de fluxo no figma, marcar reunião com @uira @diegonrojas @RaniGub para alinhamento e validação.

**Comment by Narapessoa** [comment]
@diegonrojas formulário liberado para ser configurado no Mapas.

**Comment by diegonrojas** [comment]
Maravilha. Será usado assim que tivermos a interface do formulário.
