### ISSUE TITLE
[OPORTUNIDADES] Não há texto descritivo da seção

### ISSUE THREAD

**Issue by juscoton** [LabCDBr/gestao#271]
**Contexto:** Embora o título seja auto-descritivo, seria interessante um texto explicativo da seção indicando de maneira breve o que é uma Oportunidade para a plataforma Mapas.
**Ocorrência:** desktop e mobile
**Recomendação:** Inserir texto descritivo da seção.
**Link da seção:** https://mapas.tec.br/oportunidades/

**ESCOPO:**
- [x] Criar texto descritivo da seção (narrativas)
- [ ] Inserir texto descritivo da seção (tecnologias)

**Comment by RaniGub** [comment]
@Narapessoa

**Comment by Narapessoa** [comment]
@marlioesmeraldo, por gentileza, analisar essa demanda e encaminhar..

**Comment by marlioesmeraldo** [comment]
@RaniGub qual o link da seção?

**Comment by RaniGub** [comment]
> @RaniGub qual o link da seção?

Oi @marlioesmeraldo é a seção Oportunidades

https://mapas.tec.br/oportunidades/

![Captura de Tela 2024-04-30 às 14 50 00](https://github.com/LabCDBr/gestao/assets/79097920/250f0804-6c82-4055-bc47-e89802c83870)

**Comment by marlioesmeraldo** [comment]
Texto descritivo pronto @juscoton  e revisado pelo @uira em https://docs.google.com/document/d/1ATR3L5YnsKFMVgKJMUChf8I7VV9qvjhnqNTai4mVndE/edit?usp=sharing

**Comment by emillecatarine** [comment]
Vamos repensar a inserção desses textos na análise individual das entidades.
