### ISSUE TITLE
[OPORTUNIDADES] Padronização dos botões

### ISSUE THREAD

**Issue by juscoton** [LabCDBr/gestao#277]
Contexto: Padronização dos botões
Ocorrência: web e mobile
Recomendação: Ao abrir o edital, botão “Fazer inscrição” é enorme e fora do padrão dos demais botões utilizados. Necessário padronizar os botões.

Problema classificado pelo Design com nível de criticidade médio

Escopo

- [ ] padronizar altura, margens e fontes de todos os botões

**Comment by RaniGub** [comment]
Essa atividade certamente fará parte do escopo da prototipação das jornadas, então no momento da sugestão da interface, ela será indiretamente atendida.
