### ISSUE TITLE
[PROD 6.1] Guia de adoção do Mapas Culturais para gestão cultural

### ISSUE THREAD

**Issue by thaisbtoscano** [LabCDBr/gestao#28]
## Meta 6 > Produto 1
1 (um) documento publicado no repositório do projeto contendo o guia público de adoção do Mapas Culturais
para gestão cultural.

### Escopo
- [x] #82
- [x] #83
- [x] #84
- [x] #143
- [x] #85
- [x] #86
- [x] #144
- [ ] #87
- [ ] #88

### Critérios de aceitação
- [x] Primeira versão do documento em ambiente colaborativo
- [x] Primeira versão da jornada de adoção

### Entrega
[Doc publicado no repositório](https://github.com/LabCDBr/gestao/blob/main/produtos/6-1-Guia%20p%C3%BAblico%20de%20Ado%C3%A7%C3%A3o%20do%20Mapas%20Culturais%20para%20Gest%C3%A3o%20Cultural.odt)

**Comment by Sircorujo** [comment]
O levantamento das informações sobre as experiências de adoção do Mapas Culturais foi realizado por meio de pesquisa realizada pelo MinC [Slides 11 e 12].
O levantamento foi complementado por levantamentos de fonte secundária, bibliográfica e pesquisa na Internet.

**Comment by Sircorujo** [comment]
- [ ] Revisar estrutura básica do documento (que está no drive)
- [ ] Convidar o GT de articulação para a retomada das reuniões na semana do dia 01 de abril.
- [ ] Apresentar a primeira versão do guia e do macroprocesso de adoção da solução digital para colher as opiniões
- [ ] Receber os dados brutos da pesquisa que já fizeram para sistematizar e incluir no panorama tecnológico (que consta no documento).
- [ ] segunda reunião na semana do 08 de abril para devolutiva das correções feitas no documento e no processo a partir da sugestão do GT

**Comment by doutorsocrates90** [comment]
Produto finalizado e entregue:
https://github.com/LabCDBr/gestao/blob/main/produtos/M6%20P1%20-%20Guia%20de%20ado%C3%A7%C3%A3o%20do%20Mapas%20Culturais.pdf
