### ISSUE TITLE
[OPORTUNIDADES] Categorização de informações

### ISSUE THREAD

**Issue by juscoton** [LabCDBr/gestao#287]
Contexto: informações não estão categorizadas. 
Ocorrência: web
Recomendação: Ao acessar o edital, as informações não estão categorizadas.  Recomenda-se delimitar a timeline do lado direito com borda e posicionar o “Publicado por” e “Compartilhar” ao final do conteúdo do edital, alinhado do lado esquerdo.

Problema classificado pelo Design com nível de critidade baixo

Escopo
 - [ ] categorizar as informações
 - [ ] delimitar área da timeline do edital
 - [ ] reposicionar elementos ao final do conteúdo do edital do lado esquerdo

**Comment by RaniGub** [comment]
@emillecatarine, assinei você nessa. Faremos a tela com os componentes já disponíveis no Figma.

**Comment by juscoton** [comment]
seria a proposição de uma nova estrutura, o que está no Figma atende

**Comment by RaniGub** [comment]
Olá @emillecatarine você pode avaliar essa issue? Alguma que você criou tem o escopo parecido? Estamos com esse débito técnico. Se não, você pode disponibilizar para seguirmos essa para tecnologias? Como a @juscoton que identificou, ela pode dar esse contexto. Obrigado.

**Comment by RaniGub** [comment]
Essa tarefa será atendida indiretamente na fase de prototipação da jornada do Agente Cultural nas oportunidades.
