### ISSUE TITLE
[PERFIL] Sugerir nova experiência e interface

### ISSUE THREAD

**Issue by juscoton** [LabCDBr/gestao#288]
**Contexto:** Qualidades e especificações do perfil podem ser melhor apresentadas
**Ocorrência:** web e mobile
**Recomendação:** Recomenda-se o redesign da tela, para melhorar a arquitetura de informação e deixá-la mais atrativa. Entender se é possível/viável refazê-la. Sugere-se a adaptação para um formato similar ao de rede social.

Problema classificado pelo Design como nível de criticidade médio

Escopo

- [ ] Time de Design refazer a interface.

**Comment by juscoton** [comment]
A proposta que está no figma é satisfatória @RaniGub

**Comment by RaniGub** [comment]
@emillecatarine gostaria que você fizesse uma avaliação junto às sugestões da @juscoton. Vocês podem marcar um momento. O escopo falta especificações e protótipo para possibilitar a implementação.

**Comment by RaniGub** [comment]
Essa tarefa foi despriorizada. Devemos entender no desenrolar do projeto o tempo que temos para atendê-la.

**Comment by RaniGub** [comment]
O método de desenvolvimento e interface do time de design sofreu modificação, dessa forma, as issues que forem sendo criadas a partir de agora eventualmente trarão escopo de issues antigas.
