### ISSUE TITLE
Banco de pessoas para os testes de usabilidade

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#304]
**Contexto**
Precisamos fazer um movimento conjunto para compreender quem são as pessoas que irão participar dos testes de usabilidade. Enquanto não conseguimos a caracterização das pessoas por amostragem, podemos fazer uma articulação via GTs das pessoas que tem interesse expontâneo de participar dos testes e/ou indicações.

- [x] Criar um forms para cadastro de interessados via GTs

**Informação complementar**
- Gestora Cultural
- Gestora de Fomento
- Agente Cultural
- Avaliadora
- Público
- Administradora do Sistema
- Gestora de desenvolvimento (?)
- Gestora de Infraestrutura (?)

Link para o forms de cadastro de interessados:
https://docs.google.com/forms/d/1W8viRjlJkY1ylz7Ryz5YC0SHL38wwSQqClSpQ89nzKo/edit

Após revisão de formulário é preciso que a Narrativas desenvolva uma chamada para os testes, esse alinhamento pode ser feito com a @juscoton. Se necessário, aproximar o Alexandre do MinC, ele vai apoiar o processo.

**Comment by Jualmeida1212** [comment]
Oi Rani, 
Sugerimos acrescentar 3 tipos de agentes culturais: Pessoa Física, Pessoa Jurídica e Coletivo. É necessário também ter o perfil Gestor de Fomento.

**Comment by RaniGub** [comment]
> Oi Rani, Sugerimos acrescentar 3 tipos de agentes culturais: Pessoa Física, Pessoa Jurídica e Coletivo. É necessário também ter o perfil Gestor de Fomento.

Oi Ju, obrigado. Vamos considerar.

**Comment by Andreqlp** [comment]
Falando especificamente do usuário que vai utilizar o Mapas para operacionalizar, enxergo os seguintes papéis:

### Equipe gestora do edital:
- Gestor do fomento: equipe responsável pela elaboração do edital, instrumento que vai definir as regras de participação, avaliação e inscrição. Nesse momento são definidos; o formato da comissão de avaliação, os critérios e os campos para a criação da ficha de inscrição. Provavelmente o gestor da equipe não conhece bem a plataforma do Mapas, mas interferem diretamente em como a ferramenta será operacionalizada.
- Técnico do fomento: responsável por formatar a ficha de inscrição, criar o projeto e oportunidade no mapas e acompanhar as inscrições. O cadastro do campo de categoria é particularmente importante pois ele irá definir uma das opções de distribuição das inscrições entre os avaliadores. Essa pessoa também pode fazer o papel de organizar o resultado para a publicação preliminar e final, como também formatar e compartilhar os pareceres individuais.
- Testadores da ficha de inscrição: uma boa prática é compartilhar a ficha de inscrição com outras pessoas para validar se todos as perguntas estão corretas, assim como as lógicas de perguntas condicionais.
- Suporte técnico:   alguém da equipe de TI que vai auxiliar os candidatos na utilização da plataforma e resolver problemas técnicos.
- Coordenador da equipe de avaliação: configura os critérios de avaliação no mapas, adiciona e distribui as inscrições entre os avaliadores. Ele precisa acompanhar o processo de avaliação para garantir o cumprimento dos prazos e a qualidade da avaliação.
- Avaliadores: responsável por avaliar os projetos na plataforma, dependendo do método proposto ele pode se reunir com a comissão para reavaliar os projetos e responde junto com a comissão aos recursos do resultado preliminar.

Essa turma toda trabalha na secretaria e acho que podem ser diferenciada pelo tipo de edital (editais de cultura popular, editais de linguagens artísticas o mecenato), pela experiência na utilização do Mapas  (já realizou editais ou não) ou pela estrutura do órgão, talvez existam lugares que a mesma pessoa faça vários papéis.

### Proponentes
É o público mais diverso, eles podem ser diferenciados por:
- tipo de proponente como a Ju comentou (pessoa física, jurídica e coletivo)
- papel (artista beneficiado, produtor, alguém da rede de apoio tipo um parente...)
- territorialmente  (capital e interior, ou cidades de grande, médio e pequeno porte)
- idade (pessoas jovens, adultos e idosos)
- escolaridade (além da dificuldade na ferramenta a baixa escolaridade influencia no entendimento do edital)
- nível de experiência na utilização do mapas ou de participação em editais (primeira vez ou recorrente)
- acessibilidade (considerando tanto pessoas com deficiência quanto dificuldades no acesso a tecnologia)
-  acesso á tecnologia (aqui entra a questão da qualidade da internet ou do dispositivo que ela utiliza, por exemplo computador ou celular pessoal, ou então alguém que usa um equipamento numa escola)

**Comment by RaniGub** [comment]
> Falando especificamente do usuário que vai utilizar o Mapas para operacionalizar, enxergo os seguintes papéis:
> 
> ### Equipe gestora do edital:
> * Gestor do fomento: equipe responsável pela elaboração do edital, instrumento que vai definir as regras de participação, avaliação e inscrição. Nesse momento são definidos; o formato da comissão de avaliação, os critérios e os campos para a criação da ficha de inscrição. Provavelmente o gestor da equipe não conhece bem a plataforma do Mapas, mas interferem diretamente em como a ferramenta será operacionalizada.
> * Técnico do fomento: responsável por formatar a ficha de inscrição, criar o projeto e oportunidade no mapas e acompanhar as inscrições. O cadastro do campo de categoria é particularmente importante pois ele irá definir uma das opções de distribuição das inscrições entre os avaliadores. Essa pessoa também pode fazer o papel de organizar o resultado para a publicação preliminar e final, como também formatar e compartilhar os pareceres individuais.
> * Testadores da ficha de inscrição: uma boa prática é compartilhar a ficha de inscrição com outras pessoas para validar se todos as perguntas estão corretas, assim como as lógicas de perguntas condicionais.
> * Suporte técnico:   alguém da equipe de TI que vai auxiliar os candidatos na utilização da plataforma e resolver problemas técnicos.
> * Coordenador da equipe de avaliação: configura os critérios de avaliação no mapas, adiciona e distribui as inscrições entre os avaliadores. Ele precisa acompanhar o processo de avaliação para garantir o cumprimento dos prazos e a qualidade da avaliação.
> * Avaliadores: responsável por avaliar os projetos na plataforma, dependendo do método proposto ele pode se reunir com a comissão para reavaliar os projetos e responde junto com a comissão aos recursos do resultado preliminar.
> 
> Essa turma toda trabalha na secretaria e acho que podem ser diferenciada pelo tipo de edital (editais de cultura popular, editais de linguagens artísticas o mecenato), pela experiência na utilização do Mapas (já realizou editais ou não) ou pela estrutura do órgão, talvez existam lugares que a mesma pessoa faça vários papéis.
> 
> ### Proponentes
> É o público mais diverso, eles podem ser diferenciados por:
> 
> * tipo de proponente como a Ju comentou (pessoa física, jurídica e coletivo)
> * papel (artista beneficiado, produtor, alguém da rede de apoio tipo um parente...)
> * territorialmente  (capital e interior, ou cidades de grande, médio e pequeno porte)
> * idade (pessoas jovens, adultos e idosos)
> * escolaridade (além da dificuldade na ferramenta a baixa escolaridade influencia no entendimento do edital)
> * nível de experiência na utilização do mapas ou de participação em editais (primeira vez ou recorrente)
> * acessibilidade (considerando tanto pessoas com deficiência)
> * acesso á tecnologia (aqui entra a questão da qualidade da internet ou do dispositivo que ela utiliza, por exemplo computador ou celular pessoal, ou então alguém que usa um equipamento numa escola)

Muito obrigado pela colaboração André. @juscoton informação super importante!

**Comment by RaniGub** [comment]
@Narapessoa gostaria do apoio das Narrativas nesse processo.

**Comment by RaniGub** [comment]
@Narapessoa forms adicionado para sua revisão.

**Comment by RaniGub** [comment]
Como o forms já foi criado, irei integrar ele para revisão como task da issue #403

**Comment by RaniGub** [comment]
Sugestões para o formulário:
Página 1:
Os testes de usabilidade serão realizados de forma estratégica, moderados pela equipe de Design do Mapas Culturais que observará como os usuários interagem com a plataforma, quais são suas dificuldades, preferências e necessidades.
Sugestão: moderados pela equipe de Design do Projeto de Soluções Digitais para Mapeamento e Gestão Cultural da Universidade Federal do Paraná/Ministério da Cultura

Página 2:
Sua participação é de fundamental importância para a construção da nova versão do Mapas Culturais, importante ferramenta para difusão da cultura do Brasil.
Sugestão: Aqui acho que ficaria interessante um texto que motive também pessoas que não usam o Mapas a ajudar quem usa. Penso que poderia ficar assim: Sua participação é de fundamental importância para a construção de um Ecossistema de Soluções Digitais para fomento à Cultura mais eficiente. Neste recorte, destaca-se o Mapa da Cultura. Posteriormente, os resultados ficarão públicos em relatórios que também darão subsídios para possíveis melhorias em outras soluções digitais de fomento à cultura no Brasil.

Página 3:
Pergunta sobre escolaridade, para manter o padrão de mestrado e doutorado, tiraria o termo 'pós-graudação' antes de especialização. Colocaria também 'ensino superior incompleto'.
Item

@juscoton

**Comment by juscoton** [comment]
adicionei suas sugestões @RaniGub

**Comment by juscoton** [comment]
@Narapessoa Alexandre pediu que nos cards de divulgação incluíssem as logos do Minc e UFPR, feito isso, está aprovado
