### ISSUE TITLE
Identificação de melhorias | Painel de controle

### ISSUE THREAD

**Issue by emillecatarine** [LabCDBr/gestao#309]
**Contexto**
Precisamos identificar melhorias de rápida implementação para possibilitar que as funcionalidades mínimas do Mapas tenham uma experiência minimamente eficiente.

_________________________________________________________________________________________________________________

**[Legenda] Níveis de criticidade:**
Alta: está impedindo a navegação do usuário.
Média: impacta consideravelmente a experiência do usuário.
Baixa: não tem grande impacto na experiência do usuário.

_________________________________________________________________________________________________________________

**NÍVEL DE CRITICIDADE: ALTA**

 - [ ] LabCDBr/gestao#316
 **Contexto:** No perfil de usuário comum (não admin), toda ação que me leva para telas de edição / painel de controle me retorna uma página em branco. Desta forma, não consigo acessar o painel e nem editar oportunidades / agentes / eventos / espaços / projetos.
**Ocorrência:** Desktop e mobile
**Recomendação:** Corrigir bug: todas as telas devem mostrar os respectivos resultados, independentemente do tipo de perfil que está acessando.

_________________________________________________________________________________________________________________

**NÍVEL DE CRITICIDADE: MÉDIA**

_________________________________________________________________________________________________________________

**NÍVEL DE CRITICIDADE: BAIXA**

- [ ] LabCDBr/transfer#56
**Contexto:** no Painel de controle, versão mobile, são apresentadas setas de scroll para indicar ao usuário scroll lateral (seções "Inscrições recentes" e "Editados recentemente", por exemplo). Porém, em contextos com apenas um item e que o scroll lateral não se aplica, as setas ainda são apresentadas.
**Ocorrência:** mobile
**Recomendação:** Recomenda-se uma das soluções: 1) Mostrar as setas apenas em situações em que exista a possibilidade de scroll lateral; 2) Criar um tratamento visual para setas desabilitadas em situações em que não exista conteúdo suficiente para que aconteça o scroll lateral.

- [ ] LabCDBr/gestao#319
**Contexto:** No Painel de controle, para Oportunidades, Agentes, Eventos, Espaços e Projetos, existe a divisão por quantidade de entidades: Publicadas, Em rascunho, Com permissão, Arquivadas, Lixeira, Importações. Não há, porém, a indicação de quantas de cada tipo existe.
**Ocorrência:** Desktop e mobile
**Recomendação:** Inserir, ao lado do texto, o número indicativo de quantidade de entidades que se enquadram em cada tipo.

**Comment by RaniGub** [comment]
Primeira rodada de identificação finalizada.
