### ISSUE TITLE
[PROD 7.1] TR Chamadas públicas soluções digitais para mapeamento e gestão

### ISSUE THREAD

**Issue by thaisbtoscano** [LabCDBr/gestao#32]
## META 7 > Produto 1
1 (um) Termo de referência para realização de chamadas públicas na modalidade de concurso para ativação do ecossistema de soluções digitais para mapeamento e gestão

### Requisitos
- O concurso é para premiação de soluções já existentes
- TR já deve abordar as principais áreas de problemas para premiação
- Buscar colaboração com o Instituto Brasileiro de Museus - Ibram (Dalton)

### Escopo
- [x] #99
- [x] #101
- [x] #100

### Critérios de aceitação
- [ ] Minuta validada pelo MinC

### Atividades complementares
- [ ] #131 

### Entrega
[Doc publicado no repositório](https://github.com/LabCDBr/gestao/blob/main/produtos/7-1-TERMO%20DE%20REFER%C3%8ANCIA%20PARA%20EDITAL%20DE%20PREMIA%C3%87%C3%83O.odt)

**Comment by doutorsocrates90** [comment]
Produto finalizado e entregue:
https://github.com/LabCDBr/gestao/blob/main/produtos/M7%20P1%20-%20TR%20Concurso%20Ativa%C3%A7%C3%A3o%20Ecossistema%20Solu%C3%A7%C3%B5es.pdf
