### ISSUE TITLE
Mapeamento de Jornada | Gestora do Fomento

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#347]
**Escopo**
Precisamos compreender a jornada da Gestora de Fomento

- [x] Realizar entrevista
- [x] Sistematização de informações
- [x] Desenhar jornada
- [ ] Validação Final (Wash, Uirá, Rani e Ju)

**Informações complementares**
Pessoa de referência: Sofia
Verificar se é necessário realizar o Teste de Usabilidade após a entrevista

- [x] Entrevista Agendada

**Comment by juscoton** [comment]
Roteiro de entrevista:
https://docs.google.com/document/d/1my74C3hwGHnkbpxdTXsJ0PvfUUEmHurhiDeD2Pyaywc/edit

**Comment by juscoton** [comment]
Sistematização de informações:
https://www.figma.com/design/d4Lfl4BcgzqK7VexRVtLvT/Jornadas-dos-Usu%C3%A1rios?node-id=69%3A1415&t=ts63BexX0DI6J1pY-1

**Comment by juscoton** [comment]
Desenho de jornada finalizado:
https://www.figma.com/design/d4Lfl4BcgzqK7VexRVtLvT/Jornadas-dos-Usu%C3%A1rios?node-id=479-796&t=7S7LDEOtzdevanoW-1

Obs.: ainda falta validação, que será feito posteriormente pois essa jornada foi despriorizada por Juliana.

**Comment by RaniGub** [comment]
Tarefa concluída.
