### ISSUE TITLE
Realizar escuta em comunidade sobre identidade do Mapas

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#353]
Inicialmente estão planejados dois encontros de governança da comunidade/Rede Mapas com objetivo de aproximação, escuta e apresentação do plano de governança do projeto **Soluções Digitais para Mapeamento e Gestão Cultural**, bem como colher insumos para os próximos passos do plano e execução das ações. 

- #203 
- #205

**Comment by Narapessoa** [comment]
Os dois encontros planejados foram realizados conforme descrito nas issues. 
Os próximos encontros serão para apresentação do modelo de governança. O planejamento desses encontros será realizado em outro épico.

**Comment by marlioesmeraldo** [comment]
Duas reuniões realizadas conforme evidências nas tarefas da descrição.
