### ISSUE TITLE
Redigir textos para cada conceito da identidade do Mapas

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#354]
Redigir textos conceituando:
- Mapas: Software / Produto
- Rede Mapas: Ecossistema
- TED Soluções Digitais: Projeto

Entregas:
- [x] Texto de uma lauda para site
- [x] Textos curtos para redes sociais
- [x] Release
- [x] Revisão interna pela equipe do projeto
- [ ] Validação do MinC (Alexandre Santos)

**Comment by marlioesmeraldo** [comment]
Minuta concluída e enviada para revisão do @uira.

Evidência:
https://docs.google.com/document/d/11wXhbqGllFmdHMXxy-2ZCgdN3VROg3F27FOzwu4ZEHc/edit?usp=sharing

**Comment by marlioesmeraldo** [comment]
Texto em revisão com @uira e @marlioesmeraldo

**Comment by marlioesmeraldo** [comment]
Refinamento realizado. Será agendada reunião com o @uira para alinhar as últimas pendências e finalizar o documento para entrega.

**Comment by marlioesmeraldo** [comment]
Mais uma etapa de revisão concluída com o @uira. Falta só finalizar o texto para entregar a primeira versão.

**Comment by marlioesmeraldo** [comment]
Texto revisado pelo @uira e pelo @marlioesmeraldo e finalizado para encaminhamento.

EVIDÊNCIA:
https://docs.google.com/document/d/11wXhbqGllFmdHMXxy-2ZCgdN3VROg3F27FOzwu4ZEHc/edit?usp=sharing

**Comment by marlioesmeraldo** [comment]
Encaminhei o texto para validação do Alexandre Santos da SGE do Minc.

**Comment by marlioesmeraldo** [comment]
Alexandre solicitou revisão da @sofiamettenheim e @Jualmeida1212 .

**Comment by marlioesmeraldo** [comment]
Em reunião com o @uira foi definido que iremos publicar no site do projeto e ajustaremos conforme feedback do MinC.

**Comment by Jualmeida1212** [comment]
Olá pessoal,

Trata-se da identidade da Rede Mapas, não do nosso projeto. Sobre esse ponto, gostaria de aguardar o retorno de Sofia e levar esse assunto para reunião de gestão.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
