### ISSUE TITLE
Finalizar texto histórico do Mapas para website

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#367]

**Comment by marlioesmeraldo** [comment]
Texto em desenvolvimento em: https://docs.google.com/document/d/10d2gbj5s3mgkrSUVi-zMjSzL0--gbPMrQpXMDsXjkQ0/edit?usp=sharing

**Comment by marlioesmeraldo** [comment]
Incorporados novos marcos na linha do tempo.

**Comment by marlioesmeraldo** [comment]
Reunião realizada com @MayalaFernandes para encaminhar novas informações ao documento. Nova etapa de coleta de informações do histórico está próxima do encerramento para finalização dos textos na sequência.

**Comment by marlioesmeraldo** [comment]
Concluída a etapa de inserção de todas as novas informações das referências coletadas na pesquisa por @marlioesmeraldo e @MayalaFernandes . Em seguida, será realizada revisão e finalização do documento.

**Referências**
https://repositorio.ufc.br/bitstream/riufc/69064/1/2021_tcc_pnaraujo.pdf 
https://institutotim.org.br/2016/09/20/mapas-em-congresso-internacional/ 
https://www.articaonline.com/wp-content/uploads/2016/09/Gcultural2016-Mesa1-Mapas-Culturais.pdf 
https://estudiolivre.org/tiki-view_blog.php?blogId=182 
http://wiki.nosdigitais.teia.org.br/Mapsys 
https://celacc.eca.usp.br/sites/default/files/media/tcc/software_livre_cultura_digital_e_plataformas_colaborativas_-_thais_rigolon.pdf 
http://www.realp.unb.br/jspui/bitstream/10482/16149/1/2014_ValeriaCruzVianaLabrea.pdf 
https://www.passeidireto.com/arquivo/81140740/2016-mapas-culturais-thais-rigolon 
https://hackmd.io/@thiagopaixao/HJiDwx_zY 
https://vimeo.com/14023400 
https://pt.slideshare.net/f3lipecabral/mapeamento-cultural-no-brasil 
http://sniic.cultura.gov.br/wp-content/uploads/2015/11/sniic.pdf 
https://x.com/CulturaGovBr/status/254298149122895872 
https://cultura-ceara.gitbook.io/tutorial-para-o-usuario-do-mapa-cultural/primeiros-passos/sobre-o-mapa-cultural-do-ceara 
http://wiki.nosdigitais.teia.org.br/Mapeamento_Cultural_no_Brasil_-_Entrevista_com_Uir%C3%A1_Por%C3%A3   
https://institutotim.org.br/projetos/mapas-culturais/   
https://institutotim.org.br/?s=mapas 
https://t.me/RedeMapas/6836  
https://docs.google.com/presentation/d/1vPl0oqftymVqI7X3dioMcJw3p47nOyv64vory0eVq78/edit#slide=id.g1e8814d6967_0_140 
https://estudiolivre.org/repo/7521/compendio_completo.pdf  Página 225

**Comment by MayalaFernandes** [comment]
Iniciada a revisão e finalização do documento de Histórico da Rede Mapas

**Comment by MayalaFernandes** [comment]
Finalização a revisão do Histórico e a sugestão de novas atividades na linha do tempo

**Comment by marlioesmeraldo** [comment]
Finalizada a minuta do histórico. Solicitamos revisão do @uira para darmos encaminhamento.

https://docs.google.com/document/d/10d2gbj5s3mgkrSUVi-zMjSzL0--gbPMrQpXMDsXjkQ0/edit?usp=sharing
