### ISSUE TITLE
Adição de protótipos do figma | Subissues da issue #187: Espaços

### ISSUE THREAD

**Issue by emillecatarine** [LabCDBr/gestao#370]
Criar protótipos de alta fidelidade no Figma para auxiliar a compreensão dos devs nas issues criadas visando melhoria de usabilidade e interface da plataforma mapas.

**Comment by RaniGub** [comment]
O método de desenvolvimento e interface do time de design sofreu modificação, dessa forma, as issues que forem sendo criadas a partir de agora eventualmente trarão escopo de issues antigas.
