### ISSUE TITLE
Relacionamento das jornadas com o Fluxo de Fomento

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#373]
**Contexto**
Temos que disponibilizar ao MinC as jornadas com relacionamento com o Fluxo de Fomento.

**Escopo**
- [x] Marcar apresentação e tira-dúvidas sobre o Fluxo com alguém do MinC

 Inserir informações de relacionamento na Jornada com o Fluxo de Fomento
- [x] #154
- [x] #155
- [x] #156
- [ ] #252
- [ ] #159
- [ ] #347
- [ ] #439
- [ ] #456 
- [ ] #457

Quais as funcionalidades mínimas para atendimento ao fluxo de fomento ao fim do mapeamento de jornadas? A forma que a jornada se apresenta hoje, atende? Quais os Gaps? 

Podemos qualificar melhor os resultados com o mapeamento de necessidades e testes de usabilidade.

**Comment by RaniGub** [comment]
@juscoton @emillecatarine @drabelodesign segue link do vídeo explicando o Fluxo de Fomento. Podem ver a parir de 1h01min. Aqui é o contexto da reunião de terça que servirá como tira-dúvidas.

https://we.tl/t-oCC9NgNaqu?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05

**Comment by juscoton** [comment]
Raia do fluxo de fomento adicionada ao fluxo do Agente Cultural.

**Comment by RaniGub** [comment]
Oportunidades essenciais ao Fluxo de Fomento já adicionadas nas respectivas jornadas priorizadas. As demais ficam para futuros relacionamentos.
