### ISSUE TITLE
Propor arquitetura da informação dos websites do Mapas

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#405]
Fazer uma proposta da arquitetura de informações integrada dos sites e páginas relacionadas ao projeto (Rede, Produto, Instância e Projeto).

**Comment by diegonrojas** [comment]
Opa @lpirola e @uira enviei uma proposta para começarmos a organizar o local para uma 2ª instância do  Mapas, mais focada em demonstração e testes sobre o Mapas... Que poderia ser em um subdomínio como experimente.mapas.tec.br... Ai a raiz do domínio (mapas.tec.br) ficaria como o ambiente para realizarmos o mapeamento das Soluções Digitais

**Comment by marlioesmeraldo** [comment]
Proposta inicial criada e encaminhada para validação do @uira e posterior transferência para o Figma: https://docs.google.com/document/d/1xRuxfSjVlTSDaAWFh110Hivqy2CVg7FUlKyuueAy7s0/edit?usp=sharing
