### ISSUE TITLE
[ÉPICO] Identificação de melhorias | Oportunidades

### ISSUE THREAD

**Issue by emillecatarine** [LabCDBr/gestao#415]
**Escopo**
Precisamos mapear os bugs da seção oportunidades para disponibilizar o ambiente para os testes de usabilidade.

[Link da planilha com mapeamento de bugs](https://docs.google.com/spreadsheets/d/1VEcOaniWVkLsYMsycvSl9ZnWtgeDO2JaXSbFrzWZIvE/edit#gid=0)

[Link do figma com nova proposta de configuração de fases da oportunidade](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Style-Guide-Mapas?node-id=17-81&t=BRsmHwmo3Rs4lNuT-1)

Regras para preenchimento de datas no campo oportunidade: 

- [ ] LabCDBr/transfer#103
**Contexto:** Atualmente, é possível cadastrar uma oportunidade com período de inscrição em datas já passadas. Sendo assim, o usuário pode cadastrar uma oportunidade com o período de inscrição já fechado.
**Ocorrência:** desktop e mobile.
**Recomendação:** não permitir selecionar datas passadas como possível período de inscrição (início e fim) e/ou publicação de resultado. 
**Prioridade:** média

- [ ] [OPORTUNIDADE] Não permitir que as fases da oportunidade ocorram após o término do evento/projeto vinculado
**Contexto:** Em oportunidades vinculadas à projetos/eventos, atualmente posso selecionar um período de inscrição e divulgação do resultado que excede o prazo do projeto/evento.
**Ocorrência:** desktop e mobile.
**Recomendação:** não permitir selecionar como período de inscrição ou publicação de resultados as datas posteriores à finalização do projeto/evento. Se o usuário tentar clicar em datas futuras (que devem estar desabilitadas) ou passar o mouse (hover), se possível, mostrar tooltip com o seguinte aviso: "Excede ao período de realização do evento ou projeto vinculado". 
**Prioridade:** média

- [ ] LabCDBr/transfer#104
**Contexto:** Na inscrição de uma oportunidade do tipo "Festival" (no link https://mapas.tec.br/oportunidade/33/#info, clicar em "fazer inscrição), existe um campo sem rótulo específico (rótulo atual: "nome do campo") na inscrição da oportunidade. O campo é obrigatório e não há clareza para o usuário do que deve ser preenchido para prosseguir.
**Ocorrência:** desktop e mobile.
**Recomendação:** Existe no banco de dados o registro de qual deveria ser o rótulo desse campo? Se sim, por favor, atualizar o rótulo. Se não, por favor, retornar essa issue para que eu tente conseguir essa informação.
**Prioridade:** alta

- [ ] LabCDBr/transfer#105
**Contexto:** Na inscrição de uma oportunidade do tipo "Festival" (no link https://mapas.tec.br/oportunidade/33/#info, clicar em "fazer inscrição), o usuário necessita selecionar um espaço e preencher um campo sem rótulo (descrito na issue 435) para conseguir enviar a inscrição. Uma vez que ele envia a inscrição, o que ele preencheu nesse campo sem rótulo vira o nome do Espaço selecionado, mesmo que ele não tenha permissão para editar o espaço.
**Ocorrência:** Desktop e mobile.
**Recomendação:** Quaisquer inscrições feitas nesse campo sem rótulo não devem alterar o nome do espaço selecionado. Corrigir bug.
**Prioridade:** alta

- [ ] LabCDBr/transfer#106
**Contexto:** Na edição de uma oportunidade (especificamente na seção "Informações") existe, na barra da direita, um campo chamado "Tags". Esse campo está marcado como obrigatório, mas é possível cadastrar a oportunidade sem cadastrar nenhuma tag.
**Ocorrência:** desktop e mobile.
**Recomendação:** Remover asterisco de obrigatoriedade do campo "Tags" e manter o campo não obrigatório.
**Prioridade:** média

- [ ] LabCDBr/transfer#107
**Contexto:** Enquanto uma oportunidade está em rascunho, fica o aviso "Este oportunidade está em rascunho. Você Você precisa publicar para exibir para todas as pessoas" (print abaixo).  Quando eu publico essa oportunidade, porém, o aviso permanece, deixando a impressão de que a ação de publicar não foi efetiva.
**Ocorrência:** desktop e mobile.
**Recomendação:** Excluir o aviso quando a oportunidade for publicada.
**Prioridade:** média

- [ ] LabCDBr/transfer#121
**Ocorrência:** desktop e mobile.
**Contexto:** Quando publico uma oportunidade, eu continuo na página de edição. Se eu clico novamente em publicar, o aviso de erro me informa que não tenho permissão para executar essa operação.
**Recomendação:** O ideal é que, quando o usuário clicar em "salvar e publicar" (e clicar em "sim" na modal de confirmação), ele seja automaticamente direcionado para a página da oportunidade publicada. Desta forma, ele não teria a oportunidade de clicar uma segunda vez no botão antes de trocar de tela, o que resolveria o bug acima descrito.

**Comment by RaniGub** [comment]
O mapeamento inicial de bugs foi finalizado. @emillecatarine por gentileza, verifique a criação da issue "[OPORTUNIDADE] Não permitir que as fases da oportunidade ocorram após o término do evento/projeto vinculado". Voltei as issues dessa tarefa para a coluna "A refinar", com exceção da #449 que já tinha protótipo, e assinei novamente o time de design até disponibilizarmos os demais protótipos, após isso, podemos retornar para UX/UI realizado e assinar as "Tecnologias". Verifiquei a planilha que você disponibilizou e não encontrei as demais lá, por isso fiz esse movimento.

Aproveito para informar que deletei a issue #462 porque podemos seguir a atualização das pendências na próprias issues, assim damos maior rastreabilidade ao Washington. Vou colocar os links no escopo da Épico de Oportunidades que será criado.

**Comment by RaniGub** [comment]
Tarefa convertida para Épico.

**Comment by RaniGub** [comment]
Primeira onda de melhorias já mapeada. As que forem surgindo serão cadastradas diretamente no repo Rede Mapas.
