### ISSUE TITLE
Realização de novas Reuniões com os GTs da Rede Mapas (Soluções Digitais para Mapeamento e Gestão Cultural)

### ISSUE THREAD

**Issue by uira** [LabCDBr/gestao#43]

**Comment by Sircorujo** [comment]
Reunião realizada em 03/04/2024 as 14:00 às 17:00 horas. Foram apresentadas a minuta inicial do guia, do TR e do macroprocesso de adoção de soluções digitais que são o documento base para o desdobramento dos indicadores.
