### ISSUE TITLE
Mapeamento de Jornada | Gestora da PNAB 1 - Sofia

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#439]
**Escopo**
Precisamos compreender a jornada da Gestora Cultural, pessoa que disponibiliza a oportunidade de fomento.
- [x] Realizar entrevista
- [x] Sistematização de informações
- [x] Desenho da Jornada
- [ ] Validação Final (Juliana Almeida, Wash, Uirá, Rani)

**Informações complementares**
Sofia dará um direcionamento sobre o que ela espera da Jornada dessa pessoa.
Sofia - Sec. Estratégica 

A intenção é desenharmos as jornadas individualmente com as pessoas e depois fazer um comparativo para chegarmos em um ponto médio de necessidades da pessoa Gestora da PNAB.

**Comment by drabelodesign** [comment]
Entrevista realizada.
Gravação disponível no link: https://drive.google.com/drive/folders/1NEBrmkPf1BX4GCIptqxF-A33PTlsTGrL

**Comment by juscoton** [comment]
Sistematização das informações:
https://www.figma.com/design/d4Lfl4BcgzqK7VexRVtLvT/Jornadas-dos-Usu%C3%A1rios?node-id=545-1041&t=N7vbPhn80MqNLB0E-1

**Comment by juscoton** [comment]
Jornada desenhada (aguardando ainda refinamento):
https://www.figma.com/design/d4Lfl4BcgzqK7VexRVtLvT/Jornadas-dos-Usu%C3%A1rios?node-id=661-1821&t=2KJWHPu5ed8VKthk-1

**Comment by RaniGub** [comment]
Tarefa finalizada.
