### ISSUE TITLE
Oficina Priorização de Dores/funcionalidades

### ISSUE THREAD

**Issue by juscoton** [LabCDBr/gestao#448]
Oificina com time de Design + Tecnologia + Sofia + Juliana para priorização das dores e funcionalidades identificadas no mapeamento de jornada do Agente Cultural e Gestor Cultural.

Escopo:
- [x] Board no figma
- [x] Realização da oficina pt. 1
- [x] Realização da oficina pt. 2

**Outras informações**
[Documento de referência do MinC ](https://docs.google.com/document/d/1egSKAf1U3g3XAsWybEAOBleUpOfngC1UFC1ux_Xqss4/edit)

**Comment by juscoton** [comment]
Board da oficina:
https://www.figma.com/design/v8Ofg9eryeU5UIQ40Fo46p/Oficina-Prioriza%C3%A7%C3%A3o-de-Dores%2Ffuncionalidades?node-id=0%3A1&t=zUKZCVB78HhDFXEU-1

**Comment by juscoton** [comment]
Reunião com gestor PNAB agendada para 22/05 às 11h.

**Comment by juscoton** [comment]
Pt. 2 da oficina agendada para o dia 11/06 às 16h30

**Comment by RaniGub** [comment]
Papo marcado para amanhã, 14/06/24, 11h, para fechar as priorizações.
Participantes: Juliana e Alexandre

**Comment by juscoton** [comment]
Agenda reagendada para 17/06.
