### ISSUE TITLE
Dashboard de indicadores

### ISSUE THREAD

**Issue by drabelodesign** [LabCDBr/gestao#455]
**Escopo**
Necessidade de criar espaço no Mapas que receba um dashboard com indicadores que reflitam o cenário cultural com informações dos agentes cadastrados na plataforma.
- [x] Reunião com time de tecnologia para alinhamento das necessidades
- [x] Refinamento com o Uirá
- [x] Levantamento das informações dos agentes coletadas pela plataforma
- [x] Prototipação de tela
- [x] Aprovação Técnica de Desenvolvimento (Victor)
- [x] Aprovação Design (Emi e Fabi)
- [x] Aprovação (Uirá, Wash, Rani)

**Comment by RaniGub** [comment]
@uira proposta finalizada. O @drabelodesign está tentando bater um papo com você para validação do MVP.

**Comment by drabelodesign** [comment]
Prévia do protótipo de Painel de Indicadores:
https://www.figma.com/design/5KpPbldBlEgtB0Pztq3aHd/Painel-de-Indicadores?node-id=0-1&t=0xN9lb2SODTbMMsm-1

**Comment by RaniGub** [comment]
> Prévia do protótipo de Painel de Indicadores: https://www.figma.com/design/5KpPbldBlEgtB0Pztq3aHd/Painel-de-Indicadores?node-id=0-1&t=0xN9lb2SODTbMMsm-1

@vicmagpac proposta de MVP finalizada. @uira deixe seus comentários. O Danilo estará dedicado ao desenhos de Fluxos nessa Sprint 6, qq modificação que requeira maior esforço, por gentileza, alinhe comigo. Se não for algo muito essencial, deixamos para outro momento. Não podemos ter pontos fora da curva nesses próximos dias.

**Comment by drabelodesign** [comment]
@RaniGub na quinta eu conversei com o Victor e com o Uirá e ambos aprovaram a proposta de MVP.
Imagino que o @wforte88 precisará validar em algum momento tb.

**Comment by RaniGub** [comment]
Versão inicial finalizada. Com as descobertas do time de dados e expectativas do MinC, o MVP poderá receber novas atualizações.
