### ISSUE TITLE
Mapeamento de Jornada | Gestora da PNAB 2 - Teresa

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#456]
**Escopo**
Precisamos compreender a jornada da Gestora Cultural, pessoa que disponibiliza a oportunidade de fomento.
- [x] Realizar entrevista
- [x] Sistematização de informações
- [x] Desenho da Jornada
- [ ] Validação Final (Juliana Almeida, Wash, Uirá, Rani)

**Informações complementares**
Sofia dará um direcionamento sobre o que ela espera da Jornada dessa pessoa.
Teresa - Diretoria de Fomento 

A intenção é desenharmos as jornadas individualmente com as pessoas e depois fazer um comparativo para chegarmos em um ponto médio de necessidades da pessoa Gestora da PNAB.

**Comment by juscoton** [comment]
Entrevista agendada para 24/05

**Comment by juscoton** [comment]
Sistematização de informações:
https://www.figma.com/design/d4Lfl4BcgzqK7VexRVtLvT/Jornadas-dos-Usu%C3%A1rios?node-id=547-1194&t=NRZHp4mOU6Ub0M6y-1

**Comment by juscoton** [comment]
Jornada desenhada (aguardando ainda refinamento):
https://www.figma.com/design/d4Lfl4BcgzqK7VexRVtLvT/Jornadas-dos-Usu%C3%A1rios?node-id=661-1821&t=2KJWHPu5ed8VKthk-1

**Comment by RaniGub** [comment]
Tarefa finalizada.
