### ISSUE TITLE
Mapeamento de Jornada | Gestora da PNAB 3 - Thiago

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#457]
**Escopo**
Precisamos compreender a jornada da Gestora Cultural, pessoa que disponibiliza a oportunidade de fomento.
- [ ] Realizar entrevista
- [ ] Sistematização de informações
- [ ] Desenho da Jornada
- [ ] Validação Final (Juliana Almeida, Wash, Uirá, Rani)

**Informações complementares**
Sofia dará um direcionamento sobre o que ela espera da Jornada dessa pessoa.
Thiago - Diretoria de Assistência

A intenção é desenharmos as jornadas individualmente com as pessoas e depois fazer um comparativo para chegarmos em um ponto médio de necessidades da pessoa Gestora da PNAB.

**Comment by juscoton** [comment]
Entrevista agendada para 28/05 11h

**Comment by RaniGub** [comment]
Após algumas tentativas de reunião, não foi possível coletar informações essenciais ao processo. Dessa forma, a Jornada foi finalizada com informações da Sofia, Juliana, Teresa e Alexandre.
