### ISSUE TITLE
Criação de protótipos (versão inicial): configuração de fases da oportunidade

### ISSUE THREAD

**Issue by emillecatarine** [LabCDBr/gestao#462]
Grande parte dos bugs sugeridos na issue #415 exigem a criação de protótipos para garantir maior clareza ao desenvolvedor para a aplicação de melhorias.
**Escopo:** Criar protótipos com sugestões de correções/melhorias para as **configurações de fases da oportunidade** do tipo **Edital**.

**Comment by emillecatarine** [comment]
[Link da planilha com mapeamento de bugs](https://docs.google.com/spreadsheets/d/1VEcOaniWVkLsYMsycvSl9ZnWtgeDO2JaXSbFrzWZIvE/edit#gid=0) (grande parte dos bugs estão pendentes de finalização/avaliação/aprovação de protótipo para serem cadastrados)
[Link do figma com nova proposta de configuração de fases da oportunidade](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Style-Guide-Mapas?node-id=17-81&t=BRsmHwmo3Rs4lNuT-1) (em construção)

**Comment by RaniGub** [comment]
Oi @emillecatarine fizemos um alinhamento ontem e acordamos que antes do desenho do protótipo façamos o mapeamento do fluxo da experiência no FigJam apontando as etapas com as melhorias mapeadas nas Jornadas e posteriormente com as prioridades com a oficina que aconteceu essa semana. Para isso, precisamos fazer um relacionamento com o Fluxo de Fomento para saber o que já tem e o que está faltando. Passar para o protótipo agora corremos o risco de ter que redesenhar algumas coisas

**Comment by RaniGub** [comment]
Esta issue será deletada, os protótipo seguirão sendo disponibilizados no escopo da issue já criada.
