### ISSUE TITLE
Finalizar o site sobre o Projeto

### ISSUE THREAD

**Issue by diegonrojas** [LabCDBr/gestao#463]
Finalização do site: https://solucoesdigitais.mapas.tec.br/
Processar todos os apontamentos e incluir o conteúdo criado sobre a Identidade da rede:  https://docs.google.com/document/d/11wXhbqGllFmdHMXxy-2ZCgdN3VROg3F27FOzwu4ZEHc/edit?usp=sharing

**Comment by marlioesmeraldo** [comment]
Feed do site do projeto (https://solucoesdigitais.mapas.tec.br/feed) integrado ao Mastodon da Rede Mapas (https://mastodon.social/@mapas) pelo Mastofeed (https://mastofeed.org/).

**Comment by marlioesmeraldo** [comment]
Website finalizado com previsão de atualizações cotidianas após uma série de alterações envolvendo:
- Arquitetura
- Layout
- Conteúdo

Atualizações pendentes:
- @lpirola configurar o SMTP
- @Jualmeida1212 enviar informações sobre os GTs
- @uira atualizar link de atividades de desenvolvimento

**EVIDÊNCIAS**


![Image](https://github.com/user-attachments/assets/f238d7cb-8334-473e-aeff-5f2e313967ac)



![Image](https://github.com/user-attachments/assets/0734afa6-4c7f-497e-a767-ff99b7019b63)



![Image](https://github.com/user-attachments/assets/34492b24-0470-4427-851f-d16c57c1e914)




![Image](https://github.com/user-attachments/assets/c0041f1b-088b-45ea-9f19-4374112a0b63)



![Image](https://github.com/user-attachments/assets/338e04f9-2b77-40d9-9c52-fc69102955aa)



![Image](https://github.com/user-attachments/assets/f38fa4c1-a1a1-4d95-9258-564c5149c8ba)



![Image](https://github.com/user-attachments/assets/ddad9d9a-2b5c-47fd-9230-f0ae28fd2199)



![Image](https://github.com/user-attachments/assets/6d571b08-4782-4021-aafc-d8ae3a4f3574)



![Image](https://github.com/user-attachments/assets/bb7abf7c-5268-4c0f-8ea2-d580320ecbb2)



![Image](https://github.com/user-attachments/assets/d2c31ea9-a3b8-4a4f-987a-ee4a3871ec07)



![Image](https://github.com/user-attachments/assets/e9d524eb-1485-4d75-8557-cb7ff7e3b3eb)




![Image](https://github.com/user-attachments/assets/e236ff55-4797-4288-a843-f07e99495705)


![Image](https://github.com/user-attachments/assets/d4ec34cb-8a70-4b6d-b8de-728f56979da4)



![Image](https://github.com/user-attachments/assets/572c171c-15bf-4299-8fd5-d0178e0e242f)
