### ISSUE TITLE
[Épico] Construção e validação de um Banco de Problemas do Fluxo de Fomento da Lei Aldir Blanc

### ISSUE THREAD

**Issue by RaniGub** [LabCDBr/gestao#49]
**Escopo**
O Banco é um repositório resultante do diagnóstico realizado na Oficina, dos problemas identificados e validados por diversas pessoas, presentes na Oficina, envolvidas no processo de aperfeiçoamento e melhoria das soluções utilizadas hoje no processo de fomento da Cultura no Brasil. Sua estruturação implicou no armazenamento e categorização dos problemas em suas singularidades e como parte do universo de desafios. A definição de grupos de problemas, agrupando problemas comuns que pertencem a áreas distintas, mas que podem ser agrupados por afinidade, tema ou persona ajudando a subsidiar as ações do projeto, de forma colaborativa e transversal, contando com a representatividade de pessoas que atuam na rede.
- [x] #112
- [x] #113
- [x] #105 
- [x] #106 
- [x] #107 
- [ ] #114

**Comment by uira** [comment]
A atividade #114 fica como débito técnico, mas não impede o fechamento. 

Parabéns time!

**Comment by RaniGub** [comment]
Os 3 problemas transversais faltantes já foram desdobrados e encaminhados para a coluna de validação.
