### ISSUE TITLE
[PROD 2.5] Auditoria de acessibilidade e mapeamento de requisitos

### ISSUE THREAD

**Issue by thaisbtoscano** [LabCDBr/gestao#490]
## Meta 2 > Produto 5
1 (um) Relatório de auditoria de acessibilidade e mapeamento de requisitos para implementação

### Escopo
- [x] Arquitetura da Informação mínima das rotas* do Mapas Culturais (v7)
- [x] Pesquisa de Métodos e Ferramentas para auditoria de Acessibilidade
- [x] Submissão de Códigos e Instâncias do Mapas nas ferramentas de avaliação de acessibilidade
- [x] Elaboração e Sistematização de Requisitos de implementação para melhoria da Acessibilidade do Mapas

- [x] LabCDBr/transfer#108
- [x] Elaboração do Relatório com Resultados das Análises de Acessibilidade
- [x] Elaboração da primeira versão do Relatório de auditoria de acessibilidade e mapeamento de Requisitos
- [ ] Revisão compartilhada do Relatório de Acessibilidade e Requisitos (MinC + Comunidade)

*Define-se como rotas a seção principal de cada funcionalidade proposta pela plataforma

### Informações complementares
https://www.figma.com/file/KrVYOyBrQzMwr29pDF7dvM/Produto-2-5---Acessibilidade?type=whiteboard&node-id=0%3A1&t=vWMvFy2d8Uvb3L1b-1

Versão de avaliação: https://redelivre.mapas.tec.br/

### Entrega
[Doc publicado no repositório](https://github.com/LabCDBr/gestao/blob/main/produtos/2-5-RELAT%C3%93RIO%20DE%20AUDITORIA%20DE%20ACESSIBILIDADE%20E%20MAPEAMENTO%20DE%20REQUISITOS.odt)

**Comment by doutorsocrates90** [comment]
Produto finalizado e entregue:
https://github.com/LabCDBr/gestao/blob/main/produtos/M2%20P5%20-%20Relat%C3%B3rio%20de%20acessibilidade.pdf
