### ISSUE TITLE
[PROD 2.4] Processo de atualização da versão do software

### ISSUE THREAD

**Issue by thaisbtoscano** [LabCDBr/gestao#491]
## Meta 2 > Produto 4
1 (um) Documento sobre o processo de atualização da versão software para mais atual incluindo banco de dados

### Escopo
- [x] LabCDBr/gestao#134
- [x] LabCDBr/gestao#135
- [x] LabCDBr/gestao#136

### Critérios de aceitação
- [x] Apresentação do documento com as recomendações técnicas de migração

### Entrega
[Doc publicado no repositório](https://github.com/LabCDBr/gestao/blob/main/produtos/2-4-PROCESSO%20DE%20ATUALIZA%C3%87%C3%83O%20DE%20VERS%C3%83O%20DO%20SOFTWARE%20MAPAS%20CULTURAIS.odt)

**Comment by doutorsocrates90** [comment]
Produto finalizado e entregue: https://github.com/LabCDBr/gestao/blob/main/produtos/M2%20P4%20-%20Processo%20de%20atualiza%C3%A7%C3%A3o%20de%20software.pdf
