### ISSUE TITLE
Estudo do relatório MGI

### ISSUE THREAD

**Issue by emillecatarine** [LabCDBr/gestao#509]
**Escopo:** Estudar o relatório do MGI e filtrar as sugestões que achamos que fazemos sentido. Mapear sugestões que podem ser atendidas nos protótipos a serem construídos para o fluxo de inscrição no edital.

**Tarefas:**
- [ ] Estudar relatório do MGI
- [ ] Mapear sugestões que podem (e concordamos que devem) ser acatadas

**Comment by emillecatarine** [comment]
Demanda movida para nova sprint pois foi despriorizada na sprint anterior (atualização do RoadMap foi prioridade).

**Comment by RaniGub** [comment]
Como padrão para todas as issues que entrarem nas próximas sprints, o time de design adotará uma avaliação para marcá-las com a tag "MGI", todas as issues que se relacionam com os apontamentos feitos no relatório. Essa visão é importante para que o MinC consiga dar uma resposta sobre o esforço do parceiro.
