### ISSUE TITLE
Publicar texto sobre identidade no site do Projeto

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#514]

**Comment by MayalaFernandes** [comment]
Atualizei as informações na aba Sobre o Projeto

**Comment by marlioesmeraldo** [comment]
Textos publicados no site do projeto. Atualizadas as páginas:
https://solucoesdigitais.mapas.tec.br/sobre-o-projeto/
https://solucoesdigitais.mapas.tec.br/
