### ISSUE TITLE
Publicar texto sobre identidade no site do Software (Produto)

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#515]

**Comment by MayalaFernandes** [comment]
![image](https://github.com/LabCDBr/gestao/assets/169054294/b9d8aca3-bbd4-491f-8771-60bcb95f263f)
https://solucoesdigitais.mapas.tec.br/sobre-o-projeto/

**Comment by marlioesmeraldo** [comment]
Texto publicado em https://software.mapas.tec.br/sobre/

![Image](https://github.com/LabCDBr/gestao/assets/8823113/50828264-bd22-431e-b19d-a0c491ed74d9)

Site em desenvolvimento.
