### ISSUE TITLE
Criar fluxo para compartilhamento diário das ações do projeto em grupos da comunidade (Boletim Soluções Digitais)

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#522]

**Comment by marlioesmeraldo** [comment]
Hoje, @hihiumy e @MayalaFernandes começaram a participar das dailies para coletar informações para produzir os boletins e definirmos os fluxos.

**Comment by marlioesmeraldo** [comment]
Proposta inicial  de boletins diários foi criada pela @MayalaFernandes e compartilhada no grupo do time:

**Boletim Soluções Digitais**
19/06/2024

👩🏻‍💻 Time de Tecnologias
- Agendamento da daily com bolsistas de tecnologia para 20/06, às 9h30.
- Realização de apresentação do showcase no MinC em desenvolvimento.
- Desk Check da atividade em execução.
- Finalização dos detalhes do PR e a atualização do banco de dados em curso.
- Realização de reunião com os times de design e tecnologia para esclarecimento de dúvidas.
- Preparação para apresentação de 20/06/2024.

📝 Time de Design
- Apresentação em desenvolvimento dos fluxos digitais iniciais e do fluxo conceitual de design, que serão mostrados ao MinC para ilustrar o funcionamento dos processos.
- Jornada da gestora de fomento próxima da conclusão.
- Redefinição das ações do time de design em curso.

📣 Time de Governança e Narrativas
- Início da produção deste boletim do projeto para distribuição nos grupos com o objetivo de dar transparência às ações do projeto.
- Realinhamento das ações táticas da equipe.
- Finalização do manual de identidade visual próxima.
- Finalização do documento histórico próxima.

📱 Resumo da Reunião de Apresentação de Protótipos de Interface
Hoje pela manhã, foi realizada a primeira reunião de apresentação de protótipos de interface. Esses protótipos são fruto do processo de descoberta, priorização e refinamento iniciado na Oficina de Design de Soluções Digitais. A oficina resultou no Banco de Problemas das Soluções Digitais de Fomento, que guiou o mapeamento das necessidades e a priorização das jornadas.

Com base nas jornadas mapeadas, foram identificadas e propostas melhorias. Após validação, essas melhorias serviram de base para a revisão da experiência atual da ferramenta e para a proposição de novas funcionalidades em telas e interfaces, representando melhorias nos fluxos e novas funcionalidades.

-----

O piloto está em discussão sobre melhor formato e periodicidade com a coordenação do projeto para refinamento dos critérios de noticiabilidade e da linguagem e definição de fluxo de publicização. A última proposta é de boletins semanais com notícias apuradas em tempo, disparadas nos canais de comunicação do projeto e grupos de WhatsApp e Telegram da comunidade.

O objetivo é dar transparência ao cotidiano de desenvolvimento do projeto com informações seguras para que a comunidade / MinC fique informada da agenda do projeto, das ações que estão sendo desenvolvidas de forma rápida e de fácil acesso.

**Comment by MayalaFernandes** [comment]
Comecei a acompanhar a gravação dos boletins e apuração dos relatos para elaboração de boletim semanal. Atualização em:
https://drive.google.com/drive/folders/1u3KEmoqY_NUwP2drhrq-9WjFdqt-g_UH

**Comment by marlioesmeraldo** [comment]
Definido em reunião com @uira o disparo e informativos diários nos grupos e publicações no site do projeto para compilação às sextas-feiras em boletins semanais.

@MayalaFernandes ficou com a atribuição de produzir os informativos e boletins a partir de sugestões de pautas minhas, da @MayalaFernandes , do @wforte88 e do @uira com validação da coordenação.

Os informativos são publicados no grupo Mapas Culturais, no site do projeto e, eventualmente, nos GTs correspondentes ao tema de cada pauta (Políticas, Tecnologias e Sustentabilidade).

**Comment by marlioesmeraldo** [comment]
Fluxo do boletim alinhado com o @uira :

1. Time de Narrativas produz o informe e envia pro grupo de narrativas;
2. ⁠Coordenação valida;
3. ⁠Time de Narrativas envia para o grupo de gestão;
4. ⁠MinC valida;
5. ⁠Time de Narrativas dispara em:
- Site do Projeto
- ⁠Grupo Mapas Culturais
- GTs da Rede Mapas⁠ (de acordo com o tema)
- ⁠Site da Rede Mapas (quando convier)
- ⁠Mídias Sociais (quando convier)

Solicitada inserção no grupo da gestão para validação dos informes.

**Comment by marlioesmeraldo** [comment]
@MayalaFernandes produziu os informes para validação:

---

Olá, pessoal! 🎉

Temos uma novidade: o site do Projeto Soluções Digitais já está disponível! 📢

Esse projeto, chamado Soluções Digitais para Mapeamento e Gestão Cultural, é uma parceria entre a Universidade Federal do Paraná (UFPR) e o Ministério da Cultura (MinC), viabilizada por um Termo de Execução Descentralizada (TED). Ele faz parte da Rede Mapas e tem como objetivo melhorar as soluções digitais de mapeamento e gestão cultural para apoiar as leis de fomento à Cultura, especialmente a Política Nacional Aldir Blanc (PNAB). 🎭📚

👉 Acesse e confira tudo no link: solucoesdigitais.mapas.tec.br 

---

Olá, pessoal! 🌟

📣 Você sabia que todas as informações sobre o andamento do TED Soluções Digitais são abertas ao público?

Você pode acompanhar diariamente as atualizações de duas formas:

1. GitHub: Acesso o link do projeto (https://github.com/orgs/LabCDBr/projects/1) para ver como os times estão se organizando, discutindo e publicando todas as ações.

2. Telegram: Junte-se ao nosso bot do Telegram (https://t.me/+p5tVPKM2vm5mZGFh) e receba todas as atualizações diretamente no seu celular, todos os dias!

Gostou? Então, escolha como quer acompanhar, fique por dentro de tudo o que está rolando, participe e compartilhe a informação.  🤝✨

---

Olá, pessoal! 🎉

Temos mais uma novidade para vocês! O documento de Histórico da Rede Mapas está atualizado! 📚📜

Agora você pode conferir em detalhes todos os momentos importantes desde a criação do Ministério da Cultura (MinC), passando pela criação do Mapsys e o lançamento do Mapas Culturais. 

A equipe de Governança e Narrativas também preparou uma linha do tempo resumida para você entender toda a trajetória da Rede Mapas. Você pode conferi-la no final do documento. 📅🚀

O Histórico da Rede Mapas está em constante construção e aprimoramento, você pode colaborar com sugestões, críticas ou correções. Basta acessar o documento e deixar seu comentário no modo de edição!

👉 Confira o histórico aqui: Histórico da Rede Mapas (link encurtado)

---

Olá, pessoal! 👀✨

Temos uma notícia empolgante chegando... Preparem-se! 

Em breve, vamos lançar um prêmio para as melhores propostas de soluções digitais relacionadas ao fluxo de fomento da cultura! 💡🎭

Fique de olho, porque essa é uma boa oportunidade de contribuir com ideias inovadoras para o nosso ecossistema cultural!

Mais detalhes serão revelados em breve. Fiquem ligados! 🔜👀

**Comment by marlioesmeraldo** [comment]
Foi criada a seção BLOG no site do projeto e a @MayalaFernandes já está publicando as informações com mais detalhes pra fazer o boletim semanal em https://solucoesdigitais.mapas.tec.br/category/blog/ 

![Image](https://github.com/LabCDBr/gestao/assets/8823113/48525b14-d1c5-4ab3-b468-1020a18b62bc)

### Textos:

**Acompanhe as ações do Projeto Soluções Digitais**
O Projeto Soluções Digitais está com todas as suas informações abertas ao público, permitindo que qualquer pessoa acompanhe o desenvolvimento e as ações realizadas pelas equipes envolvidas. Existem duas formas principais de acompanhar as atualizações diárias.

A primeira é por meio do GitHub, uma plataforma de hospedagem de código que permite a colaboração entre pessoas desenvolvedoras. Acesse o projeto [GitHub TED Soluções Digitais](https://github.com/orgs/LabCDBr/projects/1) para ver a organização dos times, discussões e publicações de todas as ações.

A segunda alternativa é o acompanhamento por meio do [grupo do Telegram](https://t.me/+p5tVPKM2vm5mZGFh), um bot que foi programado para enviar todas as atualizações do Github automaticamente para o aplicativo em tempo real.

Essas ferramentas oferecem uma maneira simples e prática de ficar por dentro de todas as novidades do projeto. Agora, é possível escolher a forma mais conveniente para participar e compartilhar informações.

---

**Site do Projeto Soluções Digitais está no ar**
O site do Projeto Soluções Digitais para Mapeamento e Gestão Cultural está disponível ao público no endereço solucoesdigitais.mapas.tec.br. Este projeto, viabilizado por meio de um Termo de Execução Descentralizada (TED), é uma parceria entre a Universidade Federal do Paraná (UFPR) e o Ministério da Cultura (MinC), articulada no âmbito da Rede Mapas.

O objetivo é qualificar o ecossistema de soluções digitais de mapeamento e gestão cultural para atender à execução das leis de fomento à cultura, com destaque para a Política Nacional Aldir Blanc (PNAB).

A iniciativa visa melhorar a infraestrutura digital, facilitando o acesso e a gestão de informações culturais em todo o país. O projeto também permite a integração de dados culturais de diversas fontes, a promoção da transparência e eficiência na gestão de recursos e apoia a implementação de políticas culturais.

O que você encontrará no site:
Sobre o projeto: Uma seção dedicada a explicar detalhadamente o Projeto Soluções Digitais. Nesta aba, os visitantes podem entender o contexto, os objetivos e os parceiros envolvidos, como a UFPR e o MinC.

Blog: Uma área onde são postadas todas as atualizações e novidades sobre o andamento do projeto. Este blog mantêm o público informado sobre os progressos, desafios e marcos atingidos pelo projeto.

Transparência: Nesta aba, é possível acompanhar o projeto em tempo real através de plataformas como Transferegov.br, GitHub, Figma e redes sociais (Mastodon, Instagram e Youtube). Também inclui acesso à documentação em desenvolvimento, o que permite que os visitantes vejam relatórios, termos de referência e auditorias.

Produtos: Uma seção dedicada aos produtos desenvolvidos pelo projeto. Nesta aba, os visitantes podem explorar as diversas soluções digitais criadas para melhorar o mapeamento e a gestão cultural no Brasil.

Cronograma de atividades: Esta aba detalha o cronograma das atividades planejadas e realizadas pelo projeto. Este recurso permite que os visitantes acompanhem o andamento das iniciativas e saibam o que está por vir.

Contato: A seção de contatos permite aos visitantes entrar em contato diretamente com a equipe e os desenvolvedores do projeto. Seja para tirar dúvidas, fazer sugestões ou obter mais informações, esta aba facilita a comunicação com os responsáveis pelo projeto.

Acesse o site [Soluções Digitais](https://solucoesdigitais.mapas.tec.br/) para saber mais sobre o projeto e conferir todas as informações e novidades.

---

**Conheça o Histórico da Rede Mapas**
O documento de Histórico da Rede Mapas foi recentemente atualizado e está disponível para o público consultar e colaborar. Esse documento pontua os marcos históricos desde a criação do Ministério da Cultura (MinC), passando pela criação de soluções digitais como o Mapsys, uma plataforma digital pioneira para mapeamento e gestão cultural, e o lançamento das primeiras versões do Mapas Culturais até chegar à expansão da identidade como Mapas e Rede Mapas.

Elaborado pela equipe de Governança e Narrativas do Projeto, o documento inclui uma linha do tempo resumida no final, para facilitar a compreensão da trajetória da Rede Mapas. Este recurso é relevante para quem deseja entender a evolução das iniciativas desenvolvidas no Brasil que nos trouxeram até aqui.

Além disso, o Histórico da Rede Mapas está em constante construção e aprimoramento. A comunidade é convidada a colaborar com sugestões, críticas ou correções. Para participar, basta acessar o documento e deixar comentários no modo de edição.

Em breve, será lançada uma página na Wikipedia com todos os detalhes do projeto, que servirá como mais um fonte de informação para quem quiser explorar a fundo a história e os conceitos da Rede Mapas.

Confira o histórico completo da Rede Mapas [acessando o documento](https://docs.google.com/document/d/10d2gbj5s3mgkrSUVi-zMjSzL0--gbPMrQpXMDsXjkQ0/edit#heading=h.ghsab2gbkyis).

**Comment by marlioesmeraldo** [comment]
Pendente de inclusão no grupo de gestão e validação do MinC para iniciar disparo.

**Comment by MayalaFernandes** [comment]
Documento atualizado com todos os informativos já produzidos até o momento:
https://docs.google.com/document/d/1VOPublFURly8LSVqS5I0-rbmLLAmwXvKNRFlHvoXzm0/edit?usp=sharing
