### ISSUE TITLE
Criar e divulgar teaser sobre o prêmio

### ISSUE THREAD

**Issue by vanuzawistuba** [LabCDBr/gestao#539]
Criar e divulgar teaser sobre o prêmio nos sites

**Comment by marlioesmeraldo** [comment]
Cards e texto-teaser disparado nos GTs:

![Imagem do WhatsApp de 2024-07-30 à(s) 18 16 33_ce1b97bc](https://github.com/user-attachments/assets/de3b021b-4c17-47d8-bb62-a048741340d9)

Salve, comunidade. 😉

Estou de volta com uma novidade incrível do projeto Soluções Digitais da UFPR e do MinC. Nos próximos dias, iremos lançar uma premiação para estimular a inovação e o desenvolvimento de soluções tecnológicas para a gestão do fomento cultural. 🏆 A ideia é estimular, reconhecer e valorizar a comunidade e o ecossistema de soluções digitais brasileiro. 🌱

Gostou? Pois se liga no site e nas mídias sociais da UFPR e do MinC para saber de tudo. 📍

Em breve, faremos o lançamento em ufpr.br e gov.br/cultura. 🔗🗺

**Comment by marlioesmeraldo** [comment]
### EVIDÊNCIAS

![Image](https://github.com/user-attachments/assets/12c3951f-8cab-454b-b391-9fc0b74e863d)

https://rede.mapas.tec.br/noticias/quer-ver-sua-ideia-transformar-as-politicas-de-fomento-a-cultura-no-brasil/

![Image](https://github.com/user-attachments/assets/17fdffe0-9c37-4275-83fc-557309c57e3b)

https://www.instagram.com/p/C-LbA3_PYIS/



![Image](https://github.com/user-attachments/assets/f17da2d1-1b6e-4af8-8a63-f73638d884c5)
