### ISSUE TITLE
Sistematização de informações para entrega do Produto 2.2

### ISSUE THREAD

**Issue by uira** [LabCDBr/gestao#55]
- [x] #148
- [ ] #149
- [ ] #150

**Informações complementares**
https://www.figma.com/file/181VOj4DVixEuGyKjfQeXT/RoadMap%2C-Fluxo-de-Fomento-e-Banco-de-Problemas?type=whiteboard&node-id=1071-3849&t=Bv48zu8KbaAul9oF-4

**Comment by RaniGub** [comment]
@wforte88 verificar se as duas tarefas dessa atividade continuam no Produto 2.2

**Comment by uira** [comment]
Continuam aqui, @RaniGub, mas vou fechar a atividade deixando aqui registrado que essas ações #149 e #150 estão pendentes e serão realizadas posteriormente, programadas em sprints futuras.
