### ISSUE TITLE
Produzir Informe com resumo da primeira reunião geral de governança dos GTs

### ISSUE THREAD

**Issue by marlioesmeraldo** [LabCDBr/gestao#559]
Coleta de informações sobre cada reunião para produzir Informe mensal ou quinzenal contendo resumo das reuniões e convites para as próximas

**Comment by vanuzawistuba** [comment]
Enviado hoje, 19/08, pela manhã, no Grupo Gestão Narrativas e Governança .

XXXXXXXXXXXXXXXXXXXXXXXXXX

Bom dia, pessoal
Tudo bem?

Conforme combinado, produzi um informe com dados da primeira e da segunda reunião e convite para a reunião do dia 21/08.

Se aprovarem, submetemos a aprovação do MinC/Juliana.

Abraços,

https://docs.google.com/document/d/1BBktGT22NePuw5aB3rrXh9zPlrhdzY8O15vBqINlXXc/edit

**Comment by vanuzawistuba** [comment]
Sugestão de Informativo para WhatsApp sobre as reuniões dos GTS
((((Informe da primeira e segunda  reunião e convite para a reunião do dia 21/08))))
Assunto: Resumo das Reuniões dos Grupos de Trabalho da Cultura e Convite para o Próximo Encontro!
Olá, equipe!
Gostaria de compartilhar um resumo das nossas primeiras reuniões dos Grupos de Trabalho da Cultura

Reunião geral dos GTS, realizada no dia 07/08, às 16h
O que rolou:
Apresentação da metodologia: Definimos como vamos trabalhar nos grupos para alcançar nossos objetivos.
Proposta inicial para o GT de governança: Discutimos como organizar e estruturar todas as nossas ações.
Tecnologia e compartilhamento: Apresentamos como vamos utilizar os grupos para trocar informações sobre as soluções digitais.
Andamento do GT de Taxonomias: Demos um update sobre o progresso desse grupo.
Reunião geral do GT 4 - Desenvolvimento de soluções digitais integradas e interoperáveis, realizada no dia 16/08, às 15h30
O que rolou:
Demonstração das novas funcionalidades: Apresentação e demonstração  das novas ferramentas do Mapas que vão  facilitar o nosso trabalho do ponto de vista do Design e da Tecnologia.
Discussão sobre a integração entre as diferentes soluções: Discutimos formas para garantir que todas as ferramentas trabalhem de forma harmoniosa.
Próximos passos: Definimos os próximos passos para o desenvolvimento e implementação das soluções.
E o que vem por aí?
Te convidamos para a próxima reunião do GT2 - Arranjos de Governança e Sustentabilidade de Soluções Digitais:

Quando: 21/08 (quarta-feira)⏰ 
Hora: 15h30
 ** Link:** https://bit.ly/46NDJN2
Vamos juntos construir um futuro mais integrado e inovador para a cultura brasileira!
#CulturaDigital #Inovação #Colaboração #GTSCultura

**Comment by vanuzawistuba** [comment]
Enviado em 21/08

XXXXXXXXXXXXXXXXXXX
Assunto: Resumo das Reuniões dos Grupos de Trabalho da Cultura e Convite para o Próximo Encontro! ⚡

Olá, equipe!😉
Gostaria de compartilhar um resumo das nossas primeiras reuniões dos Grupos de Trabalho da Cultura

Reunião geral dos GTS, realizada no dia 07/08, às 16h📢
O que rolou:
* Apresentação da metodologia: Definimos como vamos trabalhar nos grupos para alcançar nossos objetivos.
* Proposta inicial para o GT de governança: Discutimos como organizar e estruturar todas as nossas ações.
* Tecnologia e compartilhamento: Apresentamos como vamos utilizar os grupos para trocar informações sobre as soluções digitais.
* Andamento do GT de Taxonomias: Demos um update sobre o progresso desse grupo.

Reunião do GT 4 - Desenvolvimento de soluções digitais integradas e interoperáveis, realizada no dia 16/08, às 15h30📢

O que rolou:
* Demonstração das novas funcionalidades: Apresentação e demonstração  das novas ferramentas do Mapas que vão  facilitar o nosso trabalho do ponto de vista do Design e da Tecnologia.
* Discussão sobre a integração entre as diferentes soluções: Discutimos formas para garantir que todas as ferramentas trabalhem de forma harmoniosa.
* Próximos passos: Definimos os próximos passos para o desenvolvimento e implementação das soluções.

📚 E mais uma novidade! Saiu do forno o repositório com os vídeos das reuniões realizadas pelos Grupos de Trabalho da Cultura: https://solucoesdigitais.mapas.tec.br/governanca/

👉Confira também a nossa agenda da semana:

Próxima reunião do GT 1- Taxonomia do fomento à cultura:
Quando: 21/08 (quarta-feira)⏰ 
Hora: 15h30
 * Link:* https://bit.ly/4df21lu

 Próxima reunião do GT2 - Arranjos de Governança e Sustentabilidade de Soluções Digitais: 

Quando: 23/08 (quarta-feira)⏰ 
Hora: 15h30
 * Link:* https://bit.ly/46NDJN2

🛠️Vamos juntos construir um futuro mais integrado e inovador para a cultura brasileira!

#CulturaDigital #Inovação #Colaboração #GTSCultura
