### ISSUE TITLE
META 1 - PRODUTO 1 - 1 (um) Documento publicado no repositório do projeto contendo o plano de trabalho inicial ajustado à data efetiva de vigência do instrumento de descentralização;

### ISSUE THREAD

**Issue by uira** [LabCDBr/gestao#6]
# Produto 01 (Meta 01)

1 (um) Documento publicado no repositório do projeto contendo o plano de trabalho inicial ajustado à data efetiva de vigência do instrumento de descentralização;

## Elaboração do Plano de Trabalho
- https://github.com/orgs/LabCDBr/projects/1

### Documento do Plano de Trabalho
https://docs.google.com/document/d/1yS7AW3x3QZz8HqxNkmuiA5c5G4oI2Umf/edit#heading=h.cxwv3tvukv40

**Comment by uira** [comment]
Relatório entregue e aprovado pelo Ministério da Cultura.

**Comment by lpirola** [comment]
@Jualmeida1212 estamos com a dúvida sobre se as últimas alterações estão de acordo o que foi requisitado.

@deborahrebello precisamos solicitar formalmente essa entrega se já não tivermos.

**Comment by Jualmeida1212** [comment]
@lpirola @wforte88 Foi solicitado à Coordenação do Projeto - @deborahrebello - a apresentação atualizada do produto, em virtude da solicitação de aditivo de prazo e alterações nos períodos de realização dos produtos do TED.
