### ISSUE TITLE
[PROD 1.2] 1 (um) Documento publicado no repositório do projeto contendo os perfis de equipes e competências necessárias para a execução do projeto;

### ISSUE THREAD

**Issue by uira** [LabCDBr/gestao#7]
Construção dos perfis:
https://docs.google.com/document/d/14prfxue5w0NIxX6q0OFpA07gYWWWDkpf/edit#heading=h.cxwv3tvukv40

###DIVULGAÇÃO

- [x] #127
- [x] #128

**Comment by wforte88** [comment]
Produto publicado em https://github.com/LabCDBr/gestao/blob/main/produtos/M1%20P2%20-%20Perfis%20de%20profissionais.pdf
