### ISSUE TITLE
Levantamento das informações sobre as experiências de adoção do Mapas Culturais

### ISSUE THREAD

**Issue by Sircorujo** [LabCDBr/gestao#83]
Disponível em: https://github.com/LabCDBr/gestao/files/14658123/Analise.Resultados.Diagnostico.Inicial.Solucao.Digital.v2.xlsx.-.BASE.csv

**Comment by Sircorujo** [comment]
Levantamento foi realizado como atividade prévia ao primeiro encontro do GT 2 - Governança e sustentabilidade das soluções digitais.

Os resultados brutos encontram-se em: 

[Análise Resultados Diagnóstico Inicial Solução Digital.v2.xlsx - BASE.csv](https://github.com/LabCDBr/gestao/files/14658123/Analise.Resultados.Diagnostico.Inicial.Solucao.Digital.v2.xlsx.-.BASE.csv)

**Comment by Andreqlp** [comment]
Foi realizada algum análise sobre os dados levantados, como achados e recomendações de evolução para o levantamento?

**Comment by Sircorujo** [comment]
Olá André, sim, a análise está como parte da seção inicial dentro do guia, para auxiliar a apresentação do panorama tecnológico. Em breve o link do documento colaborativo estará aqui para contribuições da comunidade.
