### ISSUE TITLE
Validação da minuta do guia com GT

### ISSUE THREAD

**Issue by Sircorujo** [LabCDBr/gestao#86]
- [x] Convidar o GT de articulação para a retomada das reuniões na semana do dia 01 de abril
- [ ] Apresentar a primeira versão do guia e do macroprocesso de adoção da solução digital para colher as opiniões. Reunião em 03 de abril

**Comment by wforte88** [comment]
Convite realizado oficialmente no dia 22/03.

**Comment by Sircorujo** [comment]
Está sendo elaborada a apresentação para uso na reunião do GT no dia 03/04/2024.

**Comment by Sircorujo** [comment]
Reunião realizada, produto validado com sucesso.
